Repository SonarSource/sonar-dotnet, pull requests merged in 2019-10, with the labels that each got.

#2707 Fix S2699 FP: NUnit 3.0 TestCase + ExpectedResult
  sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/Rules/TestMethodShouldContainAssertion.cs
  sonaranalyzer-dotnet/src/SonarAnalyzer.Common/Helpers/UnitTestHelper.cs
  sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldContainAssertionTest.cs
  sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/TestMethodShouldContainAssertion.NUnit.cs
Labels: Area: C#, Area: Rules, SubType: False Positive, Type: Bug

#2716 Add repro for #2510
  sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/NonAsyncTaskShouldNotReturnNull.cs
Labels: Area: C#, Area: Rules, SubType: False Positive

#2729 Add support for VarPattern
  sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ShimLayer/SyntaxKindEx.cs
  sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ShimLayer/VarPatternSyntaxWrapper.cs
  sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/ShimLayer/WrapperHelper.cs
  sonaranalyzer-dotnet/src/SonarAnalyzer.CSharp/SymbolicExecution/CSharpExplodedGraph.cs
  sonaranalyzer-dotnet/tests/SonarAnalyzer.UnitTest/TestCases/DeadStores.cs
Labels: Area: C#, Type: Bug
