Repository SonarSource/sonar-dotnet, pull requests merged in 2023-07, with the labels that each got.

#7507 Rule S6610: implement CodeFix
  analyzers/src/SonarAnalyzer.CSharp/Rules/UseCharOverloadOfStringMethodsCodeFix.cs
  analyzers/src/SonarAnalyzer.Common/Rules/UseCharOverloadOfStringMethodsBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/UseCharOverloadOfStringMethodsTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseCharOverloadOfStringMethods.Fixed.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseCharOverloadOfStringMethods.ToFix.cs
Labels: Type: Improvement, Area: C#

#7544 Modify S6580: Update RSPEC
  analyzers/rspec/cs/S6580.html
  analyzers/rspec/vbnet/S6580.html
Labels: Sprint: MMF-3068

#7567 Migrate S2053: Scaffold the rule for the new SE
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/HashesShouldHaveUnpredictableSaltBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSaltTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp10.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp11.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.cs
Labels: Sprint: SE

#7563 Migrate S3329: Scaffold the rule for the new SE
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/InitializationVectorShouldBeRandomBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InitializationVectorShouldBeRandomTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.CSharp10.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.CSharp11.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.cs
Labels: Sprint: SE

#7573 Migrate S5773: Scaffold the rule for the new SE
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/RestrictDeserializedTypesBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/RestrictDeserializedTypesTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.JavaScriptSerializer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.LosFormatter.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
Labels: Sprint: SE

#7578 SE: Refactor ByteArrayConstraint cryptographically ByteCollectionConstraint
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Analyzers/HashesShouldHaveUnpredictableSalt.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Analyzers/InitializationVectorShouldBeRandom.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Checks/ByteArrayCheck.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/SymbolicValue.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ByteCollectionConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ConstraintKind.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/Constraints/ByteArrayConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SymbolicValues/SymbolicValue_TrySetConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
Labels: Sprint: SE

#7556 Java ITs: Remove "bulk_delete" orchestrator call
  its/src/test/java/com/sonar/it/csharp/AnalysisWarningsTest.java
  its/src/test/java/com/sonar/it/csharp/AutoGeneratedTest.java
  its/src/test/java/com/sonar/it/csharp/CasingAppTest.java
  its/src/test/java/com/sonar/it/csharp/CodeDuplicationTest.java
  its/src/test/java/com/sonar/it/csharp/CognitiveComplexityTest.java
  its/src/test/java/com/sonar/it/csharp/CoverageTest.java
  its/src/test/java/com/sonar/it/csharp/EnsureAllTestsRunTest.java
  its/src/test/java/com/sonar/it/csharp/ExternalIssuesTest.java
  its/src/test/java/com/sonar/it/csharp/IncrementalAnalysisTest.java
  its/src/test/java/com/sonar/it/csharp/IssuesOnMissingFilesTest.java
  its/src/test/java/com/sonar/it/csharp/MetricsIncludeHeaderCommentTest.java
  its/src/test/java/com/sonar/it/csharp/MetricsTest.java
  its/src/test/java/com/sonar/it/csharp/MultiTargetAppTest.java
  its/src/test/java/com/sonar/it/csharp/MultipleProjectsTest.java
  its/src/test/java/com/sonar/it/csharp/NoSonarTest.java
  its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java
  its/src/test/java/com/sonar/it/csharp/ProjectLevelDuplicationTest.java
  its/src/test/java/com/sonar/it/csharp/QualityProfileExportTest.java
  its/src/test/java/com/sonar/it/csharp/RuleParameterCustomizationTest.java
  its/src/test/java/com/sonar/it/csharp/SharedFilesTest.java
  its/src/test/java/com/sonar/it/csharp/TestProjectTest.java
  its/src/test/java/com/sonar/it/csharp/Tests.java
  its/src/test/java/com/sonar/it/csharp/UnitTestProjectTypeProbingTest.java
  its/src/test/java/com/sonar/it/csharp/UnitTestResultsTest.java
  its/src/test/java/com/sonar/it/csharp/WebConfigTest.java
  its/src/test/java/com/sonar/it/shared/CoverageTest.java
  its/src/test/java/com/sonar/it/shared/ScannerCliTest.java
  its/src/test/java/com/sonar/it/shared/TestUtils.java
  its/src/test/java/com/sonar/it/shared/Tests.java
  its/src/test/java/com/sonar/it/shared/VbMainCodeCsTestCodeTest.java
  its/src/test/java/com/sonar/it/shared/WebConfigBase.java
  its/src/test/java/com/sonar/it/vbnet/AutoGeneratedTest.java
  its/src/test/java/com/sonar/it/vbnet/CodeDuplicationTest.java
  its/src/test/java/com/sonar/it/vbnet/CoverageTest.java
  its/src/test/java/com/sonar/it/vbnet/MetricsTest.java
  its/src/test/java/com/sonar/it/vbnet/NoSonarTest.java
  its/src/test/java/com/sonar/it/vbnet/TestProjectTest.java
  its/src/test/java/com/sonar/it/vbnet/Tests.java
  its/src/test/java/com/sonar/it/vbnet/UnitTestResultsTest.java
  its/src/test/java/com/sonar/it/vbnet/WebConfigTest.java
Labels: Sprint: Java ITs

#7574 Bump jUnit from 4.13.2 to 5.9.2
  its/pom.xml
  pom.xml
  sonar-csharp-plugin/pom.xml
  sonar-dotnet-shared-library/pom.xml
  sonar-vbnet-plugin/pom.xml
Labels: Sprint: Java ITs

#7589 Reproducer for #7582 (S4158 FP)
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
Labels: Area: CFG/SE, Area: C#

#7577 Java ITs: Migrate to jUnit 5
  its/pom.xml
  its/src/test/java/com/sonar/it/csharp/AnalysisWarningsTest.java
  its/src/test/java/com/sonar/it/csharp/AutoGeneratedTest.java
  its/src/test/java/com/sonar/it/csharp/CasingAppTest.java
  its/src/test/java/com/sonar/it/csharp/CodeDuplicationTest.java
  its/src/test/java/com/sonar/it/csharp/CognitiveComplexityTest.java
  its/src/test/java/com/sonar/it/csharp/CoverageTest.java
  its/src/test/java/com/sonar/it/csharp/EnsureAllTestsRunTest.java
  its/src/test/java/com/sonar/it/csharp/ExternalIssuesTest.java
  its/src/test/java/com/sonar/it/csharp/IncrementalAnalysisTest.java
  its/src/test/java/com/sonar/it/csharp/IssuesOnMissingFilesTest.java
  its/src/test/java/com/sonar/it/csharp/MetricsIncludeHeaderCommentTest.java
  its/src/test/java/com/sonar/it/csharp/MetricsTest.java
  its/src/test/java/com/sonar/it/csharp/MultiTargetAppTest.java
  its/src/test/java/com/sonar/it/csharp/MultipleProjectsTest.java
  its/src/test/java/com/sonar/it/csharp/NoSonarTest.java
  its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java
  its/src/test/java/com/sonar/it/csharp/ProjectLevelDuplicationTest.java
  its/src/test/java/com/sonar/it/csharp/QualityProfileExportTest.java
  its/src/test/java/com/sonar/it/csharp/RuleParameterCustomizationTest.java
  its/src/test/java/com/sonar/it/csharp/SharedFilesTest.java
  its/src/test/java/com/sonar/it/csharp/TestProjectTest.java
  its/src/test/java/com/sonar/it/csharp/Tests.java
  its/src/test/java/com/sonar/it/csharp/UnitTestProjectTypeProbingTest.java
  its/src/test/java/com/sonar/it/csharp/UnitTestResultsTest.java
  its/src/test/java/com/sonar/it/csharp/WebConfigTest.java
  its/src/test/java/com/sonar/it/shared/CoverageTest.java
  its/src/test/java/com/sonar/it/shared/EnsureAllTestsRunBase.java
  its/src/test/java/com/sonar/it/shared/EnsureAllTestsRunTest.java
  its/src/test/java/com/sonar/it/shared/ScannerCliTest.java
  its/src/test/java/com/sonar/it/shared/TestUtils.java
  its/src/test/java/com/sonar/it/shared/Tests.java
  its/src/test/java/com/sonar/it/shared/VbMainCodeCsTestCodeTest.java
  its/src/test/java/com/sonar/it/shared/WebConfigBase.java
  its/src/test/java/com/sonar/it/vbnet/AutoGeneratedTest.java
  its/src/test/java/com/sonar/it/vbnet/CodeDuplicationTest.java
  its/src/test/java/com/sonar/it/vbnet/CoverageTest.java
  its/src/test/java/com/sonar/it/vbnet/EnsureAllTestsRunTest.java
  its/src/test/java/com/sonar/it/vbnet/MetricsTest.java
  its/src/test/java/com/sonar/it/vbnet/NoSonarTest.java
  its/src/test/java/com/sonar/it/vbnet/TestProjectTest.java
  its/src/test/java/com/sonar/it/vbnet/Tests.java
  its/src/test/java/com/sonar/it/vbnet/UnitTestResultsTest.java
  its/src/test/java/com/sonar/it/vbnet/WebConfigTest.java
Labels: Sprint: Java ITs

#7588 ITs: Fix race condition in MetricsIncludeHeaderCommentTest
  its/src/test/java/com/sonar/it/csharp/MetricsIncludeHeaderCommentTest.java
Labels: Sprint: Java ITs

#7596 Java ITs: Migrate to jUnit 5 - Remove initLocal
  its/src/test/java/com/sonar/it/csharp/AnalysisWarningsTest.java
  its/src/test/java/com/sonar/it/csharp/AutoGeneratedTest.java
  its/src/test/java/com/sonar/it/csharp/CasingAppTest.java
  its/src/test/java/com/sonar/it/csharp/CodeDuplicationTest.java
  its/src/test/java/com/sonar/it/csharp/CognitiveComplexityTest.java
  its/src/test/java/com/sonar/it/csharp/CoverageTest.java
  its/src/test/java/com/sonar/it/csharp/ExternalIssuesTest.java
  its/src/test/java/com/sonar/it/csharp/IncrementalAnalysisTest.java
  its/src/test/java/com/sonar/it/csharp/IssuesOnMissingFilesTest.java
  its/src/test/java/com/sonar/it/csharp/MetricsIncludeHeaderCommentTest.java
  its/src/test/java/com/sonar/it/csharp/MetricsTest.java
  its/src/test/java/com/sonar/it/csharp/MultiTargetAppTest.java
  its/src/test/java/com/sonar/it/csharp/MultipleProjectsTest.java
  its/src/test/java/com/sonar/it/csharp/NoSonarTest.java
  its/src/test/java/com/sonar/it/csharp/NoSourcesTest.java
  its/src/test/java/com/sonar/it/csharp/ProjectLevelDuplicationTest.java
  its/src/test/java/com/sonar/it/csharp/QualityProfileExportTest.java
  its/src/test/java/com/sonar/it/csharp/RuleParameterCustomizationTest.java
  its/src/test/java/com/sonar/it/csharp/SharedFilesTest.java
  its/src/test/java/com/sonar/it/csharp/TestProjectTest.java
  its/src/test/java/com/sonar/it/csharp/UnitTestProjectTypeProbingTest.java
  its/src/test/java/com/sonar/it/csharp/UnitTestResultsTest.java
  its/src/test/java/com/sonar/it/csharp/WebConfigTest.java
  its/src/test/java/com/sonar/it/shared/CoverageTest.java
  its/src/test/java/com/sonar/it/shared/ScannerCliTest.java
  its/src/test/java/com/sonar/it/shared/TestUtils.java
  its/src/test/java/com/sonar/it/shared/VbMainCodeCsTestCodeTest.java
  its/src/test/java/com/sonar/it/vbnet/AutoGeneratedTest.java
  its/src/test/java/com/sonar/it/vbnet/CodeDuplicationTest.java
  its/src/test/java/com/sonar/it/vbnet/CoverageTest.java
  its/src/test/java/com/sonar/it/vbnet/MetricsTest.java
  its/src/test/java/com/sonar/it/vbnet/NoSonarTest.java
  its/src/test/java/com/sonar/it/vbnet/TestProjectTest.java
  its/src/test/java/com/sonar/it/vbnet/UnitTestResultsTest.java
  its/src/test/java/com/sonar/it/vbnet/WebConfigTest.java
Labels: Sprint: Java ITs

#7584 Cleanup: remove Opposite implementation
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ByteCollectionConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
Labels: Sprint: SE

#7575 Migrate S2053: Implement rule logic (C#)
  analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Analyzers/HashesShouldHaveUnpredictableSalt.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/SaltSizeConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/HashesShouldHaveUnpredictableSaltBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSaltTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/Constraints/SaltSizeConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SymbolicValues/SymbolicValue_TrySetConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.cs
Labels: Sprint: SE

#7616 Migrate S2053: Implement ShouldExecute (C#)
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp9.cs
Labels: Sprint: SE

#7583 New rule S2053: Hashes should include an unpredictable salt - for VB.NET
  analyzers/rspec/vbnet/S2053.html
  analyzers/rspec/vbnet/S2053.json
  analyzers/rspec/vbnet/Sonar_way_profile.json
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
  analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.cs
  analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeMappingVB.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSaltTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.vb
Labels: Sprint: SE

#7618 Fix S2053 FN: Encoding.GetBytes
  analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/HashesShouldHaveUnpredictableSaltBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/HashesShouldHaveUnpredictableSaltTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp8.NetCore.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/HashesShouldHaveUnpredictableSalt.vb
Labels: Sprint: SE

#7590 New rule S3329: Cipher Block Chaining IVs should be unpredictable - for VB.NET
  analyzers/rspec/vbnet/S3329.html
  analyzers/rspec/vbnet/S3329.json
  analyzers/rspec/vbnet/Sonar_way_profile.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/InitializationVectorShouldBeRandomBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
  analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.cs
  analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeMappingVB.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InitializationVectorShouldBeRandomTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InitializationVectorShouldBeRandom.vb
Labels: Sprint: SE

#7580 Migrate S5773: Implement the rule in the new SE
  analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Analyzers/RestrictDeserializedTypes.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/SerializationConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/RestrictDeserializedTypesBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicRuleCheck.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/RestrictDeserializedTypesTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/Constraints/SerializationConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.JavaScriptSerializer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.LosFormatter.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
Labels: Sprint: SE

#7640 Improve S5773: Support secondary issue location for partial methods
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/RestrictDeserializedTypes.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/RestrictDeserializedTypesBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.CSharp9.cs
Labels: Type: Improvement, Area: CFG/SE, Area: C#, Sprint: SE

#7634 S2930: Add FN repro for #7635
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/DisposableNotDisposedTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DisposableNotDisposed.ILogger.cs
Labels: Type: False Negative, Area: C#

#7663 Allocations: Move stringliteral tokens array to static field
  analyzers/src/SonarAnalyzer.CSharp/Extensions/SyntaxNodeExtensions.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
Labels: Type: Performance, Sprint: Hardening

#7655 Allocations: Remove delegate allocation from IsGenerated
  analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxTreeExtensions.cs
Labels: Type: Performance, Sprint: Hardening

#7664 Allocations: Make IsUnchanged allocation free in the common case
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
Labels: Type: Performance, Sprint: Hardening

#7656 Allocations: Remove delegate allocation from IsExcluded
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
Labels: Type: Performance, Sprint: Hardening

#7651 S1186: Add FP repro for #7629
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.CSharp11.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.Comment.Fixed.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.Throw.Fixed.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/EmptyMethod.cs
Labels: Area: C#, Sprint: Hardening

#7674 Add ReportIssue overload to SymbolicRuleCheck
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicRuleCheck.cs
Labels: Sprint: SE

#7657 Migrate S2583/S2589: Scaffold the rule for the new SE
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp10.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp11.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp7.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.TopLevelStatements.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
Labels: Sprint: SE

#7689 Remove unused members in S6605
  analyzers/src/SonarAnalyzer.CSharp/Rules/InsteadOfAny.cs
  analyzers/src/SonarAnalyzer.Common/Rules/InsteadOfAnyBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/InsteadOfAny.cs
Labels: Sprint: Hardening

#7672 Migrate S2583/S2589: Implement analyzer
  analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp7.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.TopLevelStatements.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
Labels: Sprint: SE
