Repository SonarSource/sonar-dotnet, pull requests merged in 2023-05, with the labels that each got.

#7153 SE: Use file-scoped namespaces for constraints
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/BoolConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/LockConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ObjectConstraint.cs
Labels: Sprint: SE

#7157 SE: Add NumberConstraint
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ConstraintKind.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/NumberConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
Labels: Sprint: SE

#7152 UTs: Rename ResourceTests to TestResources
  analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextBaseTest.ShouldAnalyzeTree.cs
  analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextBaseTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Common/AnalyzerAdditionalFileTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/FilesToAnalyzeProviderTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/ParameterLoaderTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/ProjectConfigReaderTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarLintXmlReaderTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarLintXmlTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/UtilityAnalyzerBaseTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Resources/AnotherResources.Designer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Resources/SomeResources.Designer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/AdditionalFile.txt
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/FilesToAnalyze/EmptyFilesToAnalyze.txt
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/FilesToAnalyze/FilesToAnalyze.txt
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/FilesToAnalyze/FilesToAnalyzeWithInvalidValues.txt
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/ProjectOutFolderPath.txt
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarLintXml/All_properties_cs/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarLintXml/All_properties_vbnet/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarLintXml/Duplicated_Properties/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarLintXml/Incorrect_value_type/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarLintXml/Invalid_Xml/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarLintXml/Missing_properties/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarLintXml/Partially_missing_properties/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarLintXml/PropertiesCSharpTrueVbnetFalse/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/Invalid_DifferentClassName/SonarProjectConfig.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/Invalid_DifferentNamespace/SonarProjectConfig.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/Invalid_Xml/SonarProjectConfig.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/MissingAnalysisConfigPath/SonarProjectConfig.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/MissingFilesToAnalyzePath/SonarProjectConfig.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/MissingOutPath/SonarProjectConfig.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/MissingProjectPath/SonarProjectConfig.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/MissingProjectType/SonarProjectConfig.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/MissingTargetFramework/SonarProjectConfig.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/Path_MixedSeparators/SonarProjectConfig.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/Path_Unix/SonarProjectConfig.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/Path_Windows/SonarProjectConfig.xml
  analyzers/tests/SonarAnalyzer.UnitTest/TestResources/SonarProjectConfig/UnexpectedProjectTypeValue/SonarProjectConfig.xml
Labels: Sprint: SE

#7158 Use RuleMetadataLoader to load the rule description
  sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSonarRulesDefinition.java
  sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractRulesDefinition.java
  sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/AbstractRulesDefinitionTest.java
  sonar-dotnet-shared-library/src/test/resources/AbstractRulesDefinitionTest/Sonar_way_profile.json
  sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetSonarRulesDefinition.java
Labels: Sprint: Rule Format

#7169 SE: Add Equals and GetHashCode to NumberConstraint
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/NumberConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Constraints/NumberConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
Labels: Sprint: SE

#7173 UTs: Automatic parameter comma in SETestContext
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ExceptionCandidate.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ExceptionType.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IsNull.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ParameterReassignedConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Throw.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
Labels: Sprint: SE

#7177 Add TryGetOperands helper method
  analyzers/src/SonarAnalyzer.CSharp/Extensions/InvocationExpressionSyntaxExtensions.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Extensions/InvocationExpressionSyntaxExtensions.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeExtensions.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Extensions/InvocationExpressionSyntaxExtensionsTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
Labels: Area: VB.NET, Area: C#, Type: Tooling, Sprint: MMF-3069

#7174 SE: Add Plus- and MinusOperation for literals
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/NumberConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Constraints/NumberConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.vb
Labels: Sprint: SE

#7187 SE: Lean NumberConstraint from BinaryOperation
  analyzers/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S3900.json
  analyzers/its/expected/akka.net/Akka--netstandard2.0-S2259.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs
Labels: Sprint: SE

#7194 SE: Add MultiplicationOperation
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/NumberConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Constraints/NumberConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
Labels: Sprint: SE

#7198 SE: Learn NumberConstraint from combined Equals and NotEquals
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
Labels: Sprint: SE

#7228 S6603: use methods in the ILanguageFacade
  analyzers/src/SonarAnalyzer.CSharp/Rules/UseTrueForAll.cs
  analyzers/src/SonarAnalyzer.Common/Rules/UseTrueForAllBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/UseTrueForAll.cs
Labels: Sprint: MMF-3069

#7203 SE: Learn NumberConstraint from existing constraint
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
Labels: Sprint: SE

#7233 S2259: Add FP repro from Peach
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Labels: Sprint: SE

#6902 Make UtilityAnalyzerBase stateless by removing properties
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/AnalysisWarningAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/CopyPasteTokenAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/FileMetadataAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/LogAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/MetricsAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/SymbolReferenceAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/AnalysisWarningAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/CopyPasteTokenAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/FileMetadataAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/LogAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/UtilityAnalyzerBaseTest.cs
Labels: Type: Improvement, Area: VB.NET, Area: C#, Sprint: Hardening

#7243 Rule S6612: Fix unit tests
  analyzers/src/SonarAnalyzer.CSharp/Rules/UseLambdaParameterInConcurrentDictionary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/UseLambdaParameterInConcurrentDictionaryTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseLambdaParameterInConcurrentDictionary.CSharp8.cs
Labels: Area: C#, Sprint: MMF-3069

#7236 SE UTs: Replace ValidateTag with TagValue
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Constants.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IncrementOrDecrement.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.InvocationAttribute.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IsNull.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ParameterReassignedConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs
Labels: Sprint: SE

#7248 Update the expected csharp plugin file size range
  sonar-csharp-plugin/pom.xml
Labels: Area: C#, Sprint: MMF-3069

#7223 SE: Reset values on compound assignments
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CompoundAssignment.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.CompoundAssignment.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ParameterReassignedConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.vb
Labels: Sprint: SE

#7221 Implement S3949 logic
  analyzers/its/expected/Net7/Net7--net7.0-S3949.json
  analyzers/its/expected/akka.net/Akka--netstandard2.0-S3949.json
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.CSharp10.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
Labels: Sprint: SE

#7242 SE: Learn NumberConstraint from range comparisons
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/BranchingProcessor.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
Labels: Sprint: SE

#7252 S3949: Bump coverage
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
Labels: Sprint: SE

#7255 Fix S6612 FP: lambda parameter used inside NameOf()
  analyzers/src/SonarAnalyzer.CSharp/Rules/UseLambdaParameterInConcurrentDictionary.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/UseLambdaParameterInConcurrentDictionary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseLambdaParameterInConcurrentDictionary.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UseLambdaParameterInConcurrentDictionary.vb
Labels: Type: False Positive, Area: VB.NET, Area: C#, Sprint: MMF-3069

#7232 SE: Add BitOrOperation
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Arithmetic.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
Labels: Sprint: SE

#7262 Revert "UtilityAnalyzer: Use RegisterCompilationStartAction"
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCompilationStartAnalysisContext.cs
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSematicModelReportingContext.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/ReportingContext.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/AnalysisWarningAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.Register.cs
  analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarSematicModelReportingContextTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/UtilityAnalyzerBaseTest.cs
Labels: Sprint: Hardening

#7269 SE: Init integral variables to zero
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Conversion.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Conditions.vb
Labels: Sprint: SE

#7225 SE: Improve NumberConstraint learning from existing constraint
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.vb
Labels: Sprint: SE

#7195 SE: Add DivisionOperation
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Arithmetic.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
Labels: Sprint: SE

#7287 Fix a failing UT for S3949 based on Division
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
Labels: Sprint: SE

#7283 Fix S2259 FP: Conditional access checked for bool
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Labels: Sprint: SE

#7311 Version bump to 9.3.0
  analyzers/packaging/SonarAnalyzer.CSharp.nuspec
  analyzers/packaging/SonarAnalyzer.VisualBasic.nuspec
  analyzers/src/AssemblyInfo.Shared.cs
  analyzers/src/SonarAnalyzer.CFG/SonarAnalyzer.CFG.cs.nuspec
  its/pom.xml
  pom.xml
  scripts/version/Version.props
  sonar-csharp-plugin/pom.xml
  sonar-dotnet-shared-library/pom.xml
  sonar-vbnet-plugin/pom.xml
Labels: Sprint: SE

#7263 SE: Add RemainderOperation
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Arithmetic.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.vb
Labels: Sprint: SE
