Repository SonarSource/sonar-dotnet, pull requests merged in 2023-08, with the labels that each got.

#7698 SE: Migrate S2583/S2589 - Implement issue messages
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp7.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
Labels: Sprint: SE

#7708 Fix S2589 FP: When condition that evaluates to constant is a constant field.
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
Labels: Sprint: SE

#7711 Fix S1643 FP: should not apply when strings are not aggregated
  analyzers/its/expected/Ember-MM/scraper.EmberCore.XML-{E567C031-1F7B-4637-9B3A-806988DE50CF}-S1643.json
  analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/StringConcatenationInLoop.cs
  analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
  analyzers/src/SonarAnalyzer.Common/Rules/StringConcatenationInLoopBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/StringConcatenationInLoop.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/StringConcatenationInLoopTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringConcatenationInLoop.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringConcatenationInLoop.vb
Labels: Sprint: Hardening

#7705 Deprecation: Replace ValidateTag with TagValue (BeTrue part)
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.InvocationAttribute.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.TryCatchFinally.cs
Labels: Sprint: Hardening

#7677 Refactor HasConstraint
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyNullableValueAccessBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/LocksReleasedAllPathsBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/NullPointerDereferenceBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.Constraint.cs
Labels: Sprint: SE

#7701 Migrate S2583: Report secondary locations
  analyzers/its/expected/Automapper/AutoMapper--net461-S2583.json
  analyzers/its/expected/Automapper/AutoMapper--net461-S2589.json
  analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S2583.json
  analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S2589.json
  analyzers/its/expected/Nancy/Nancy--net452-S2583.json
  analyzers/its/expected/Nancy/Nancy--net452-S2589.json
  analyzers/its/expected/Nancy/Nancy--netstandard2.0-S2583.json
  analyzers/its/expected/Nancy/Nancy--netstandard2.0-S2589.json
  analyzers/its/expected/Nancy/Nancy.Testing--net452-S2589.json
  analyzers/its/expected/Nancy/Nancy.Testing--netstandard2.0-S2589.json
  analyzers/its/expected/Net5/Net5--net5.0-S2583.json
  analyzers/its/expected/Net5/Net5--net5.0-S2589.json
  analyzers/its/expected/akka.net/Akka--netstandard2.0-S2583.json
  analyzers/its/expected/akka.net/Akka--netstandard2.0-S2589.json
  analyzers/its/expected/akka.net/Akka.Cluster.Tools--netstandard2.0-S2583.json
  analyzers/its/expected/akka.net/Akka.Cluster.Tools--netstandard2.0-S2589.json
  analyzers/its/expected/akka.net/Akka.DistributedData--netstandard2.0-S2589.json
  analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared--netstandard2.0-S2583.json
  analyzers/its/expected/akka.net/Akka.Persistence.Sql.Common--netstandard2.0-S2589.json
  analyzers/its/expected/akka.net/Akka.Remote--netstandard2.0-S2589.json
  analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S2583.json
  analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S2589.json
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicCheckListTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp7.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.TopLevelStatements.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierTest.cs
Labels: Sprint: SE

#7641 Change TrackedSymbol to take ProgramState and resolve captures
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/NonNullableValueTypeCheck.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IInvocationOperationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Argument.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Assignment.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CompoundAssignment.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/DeclarationPattern.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IncrementOrDecrement.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ReDimClause.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/RecursivePattern.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CalculationsShouldNotOverflowBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/CryptographyRuleBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/InitializationVectorShouldBeRandomBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/LocksReleasedAllPathsBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ObjectsShouldNotBeDisposedMoreThanOnceBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/RestrictDeserializedTypesBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ExplodedNodeTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/IOperationExtensionsTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.CaptureOperation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.vb
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.LosFormatter.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/RestrictDeserializedTypes.LosFormatter.vb
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/AddConstraintOnInvocationCheck.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/PreserveTestCheck.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs
Labels: Type: Improvement, Area: CFG/SE, Sprint: SE

#7741 Deprecation: Replace ValidateTag with TagValue (Part 2)
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs
Labels: Sprint: Hardening

#7748 Fix VB 14 test
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnceTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.VB14.vb
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.vb
Labels: Sprint: SE

#7751 Migrate S2583/S2589: Update ITs
  analyzers/its/expected/akka.net/Akka.DistributedData--netstandard2.0-S2589.json
Labels: Sprint: SE

#7754 Fix S2589 FP: FlowCaptureReference in throw statement
  analyzers/its/expected/Automapper/AutoMapper--net461-S2589.json
  analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S2589.json
  analyzers/its/expected/Nancy/Nancy--net452-S2589.json
  analyzers/its/expected/Nancy/Nancy--netstandard2.0-S2589.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
Labels: Sprint: SE

#7757 Token type analyzer: Fix empty string handling
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.cs
Labels: Area: C#, Sprint: UtilityAnalyzer

#7747 TokenType: Add test cases
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Labels: Sprint: UtilityAnalyzer

#7789 Fix S2583/S2589 FP: Do not raise when condition is in the body of a lock statement.
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ConditionEvaluatesToConstantBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp8.cs
Labels: Sprint: SE

#7793 Add reproducers for S2583/S2589 issues
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp7.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp7.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.cs
Labels: Sprint: SE

#7775 TokenType: Move to Syntax based classification
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.ClassifierTestHarness.cs
Labels: Area: C#, Sprint: UtilityAnalyzer

#7809 UtilityAnalyzer: Wrong classifcation for nullable types
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Labels: Area: C#, Sprint: UtilityAnalyzer

#7813 UtilityAnalyzer: Wrong classifcations for type parameter
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Labels: Area: C#, Sprint: UtilityAnalyzer

#7812 UtilityAnalyzer: Wrong classifcations for tuple elements
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Labels: Area: C#, Sprint: UtilityAnalyzer

#7814 UtilityAnalyzer: Wrong classifications for AliasQualifiedNames
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Labels: Area: C#, Sprint: UtilityAnalyzer

#7817 UtilityAnalyzer: Annotate with performance sensitive
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
  analyzers/src/SonarAnalyzer.CSharp/SonarAnalyzer.CSharp.csproj
Labels: Area: C#, Sprint: UtilityAnalyzer

#7824 UtilityAnalyzer: Wrong classifications: ref types
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Labels: Sprint: UtilityAnalyzer

#7822 UtilityAnalyzer: Wrong classifications: value in MemberAccess
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Labels: Area: C#, Sprint: UtilityAnalyzer

#7823 UtilityAnalyzer: Wrong classifications: value in nameof
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Labels: Sprint: UtilityAnalyzer

#7797 Fix S2589 FN: Infinite for-loop
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/BranchingProcessor.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicCheckListTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.vb
Labels: Area: CFG/SE, Area: VB.NET, Area: C#, Type: CFG/SE FPs, Sprint: SE

#7887 Fix S2583 raised in our code base
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/MethodsShouldNotHaveTooManyLines.cs
Labels: Type: Improvement

#7884 SE: Check the maximum steps only for visited nodes
  analyzers/its/expected/Ember-MM/generic.EmberCore.NMT-{84B2143A-D04F-4262-923D-21AEDF86E2B7}-S2259.json
  analyzers/its/expected/Ember-MM/generic.EmberCore.NMT-{84B2143A-D04F-4262-923D-21AEDF86E2B7}-S2589.json
  analyzers/its/expected/Ember-MM/scraper.EmberCore-{EF6A550E-DD76-4F4D-8250-8598140F828B}-S3900.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
Labels: Area: CFG/SE, Sprint: SE

#7892 Java ITs: Update test to not take order of issues into consideration
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  its/src/test/java/com/sonar/it/csharp/SharedFilesTest.java
Labels: Area: SQ Plugin

#7897 Revert "Fix S2589 FN: Infinite for-loop (#7797)"
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/BranchingProcessor.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicCheckListTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Monitor.Loops.vb
Labels: Sprint: SE

#7905 Add .AddSnippet() support for .razor and .cshtml snippets
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Verifier.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/VerifierBuilder.cs
Labels: Sprint: MMF-3322 🪒

#7899 SE: Learn bool constraints from Equals with bool parameters.
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.vb
Labels: Sprint: SE

#7861 Fix S4158 FN: Learn Empty on Clear
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.vb
Labels: Type: False Negative, Area: CFG/SE, Area: VB.NET, Area: C#, Sprint: SE

#7909 Add .razor file unit test for SymbolReferenceAnalyzer
  analyzers/src/SonarAnalyzer.Common/Common/AnalyzerLanguage.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Common/AnalyzerLanguageTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/SymbolReferenceAnalyzer/Razor.razor
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/SymbolReferenceAnalyzer/ToDo.cs
Labels: Sprint: MMF-3322 🪒

#7912 Retrieve file path from pragma checksum
  analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
  analyzers/src/SonarAnalyzer.Common/Extensions/SyntaxTreeExtensions.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/SyntaxNodeExtensions.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Extensions/SyntaxNodeExtensionsTest.cs
Labels: Sprint: MMF-3322 🪒

#7933 SE: Do not learn CollectionConstraints for untracked collections
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
Labels: Sprint: SE
