Repository SonarSource/sonar-dotnet, pull requests merged in 2023-02, with the labels that each got.

#6725 S4663: Fix highlighting to remove underlying whitespaces
  analyzers/src/SonarAnalyzer.Common/Rules/CommentsShouldNotBeEmptyBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CommentsShouldNotBeEmpty.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CommentsShouldNotBeEmpty.vb
Labels: Type: Improvement, Area: C#

#6791 Bump Roslyn and NuGet dependencies
  analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/SonarAnalyzer.ShimLayer.CodeGeneration.csproj
  analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/packages.lock.json
  analyzers/src/SonarAnalyzer.SourceGenerators/SonarAnalyzer.SourceGenerators.csproj
  analyzers/src/SonarAnalyzer.SourceGenerators/packages.lock.json
Labels: Sprint: SE

#6821 Fix S2970: Fix failing tests for C# 7.3
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/AssertionsShouldBeCompleteTest.cs
Labels: Type: Bug, Area: C#

#6819 Bump MsTest to 3.0.2 and Test SDK to 17.5.0
  analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
  analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json
Labels: Sprint: SE

#6822 Update SonarLint config
  analyzers/.sonarlint/SonarAnalyzer.slconfig
  analyzers/.sonarlint/sonaranalyzer-dotnetCSharp.ruleset
Labels: Type: Tooling
