Repository SonarSource/sonar-dotnet, pull requests merged in 2023-11, with the labels that each got.

#8271 Adding missing operation wrappers and syntax kinds to the shim layer
  analyzers/src/SonarAnalyzer.CFG/ShimLayer/OperationInterfaces.xml
  analyzers/src/SonarAnalyzer.CFG/ShimLayer/SyntaxKindEx.cs
  analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/OperationLightupGenerator.cs
Labels: Type: Improvement

#8198 Update rspec.ps1 to copy test case from RSPEC
  scripts/rspec/CopyTestCasesFromRspec.ps1
  scripts/rspec/README.md
  scripts/rspec/rspec.ps1
  scripts/rspec/tests/CopyTestCasesFromRspec.Tests.ps1
Labels: Type: Tooling

#8270 Repro for S2589 FP: Simple switch block leads to multiple FPs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
Labels: Area: CFG/SE, Area: C#, Type: CFG/SE FPs

#8181 ClearTextProtocolsAreSensitive: Reuse compiled regex
  analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
Labels: Area: C#, Type: Performance

#8309 IsRedundantPrimaryConstructorBaseTypeContext: Add tests
  analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarSyntaxNodeReportingContextTest.cs
Labels: Type: False Positive, Area: C#12

#8325 Reproducer for #8324
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Labels: Area: CFG/SE, Area: C#

#8327 S2589 FP: Add reproducer for #8326
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp8.cs
Labels: Area: CFG/SE, Area: C#, Area: C#8

#8335 Fix S2259 FN: FlowCaptures in Field/PropertyReference.Instance
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExceptionCandidate.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp6.cs
Labels: Type: False Negative, Area: CFG/SE, Area: C#

#8353 S6798: Add ITs
  analyzers/its/expected/BlazorSample/BlazorSample--net7.0-S101.json
  analyzers/its/expected/BlazorSample/BlazorSample--net7.0-S108.json
  analyzers/its/expected/BlazorSample/BlazorSample--net7.0-S1144.json
  analyzers/its/expected/BlazorSample/BlazorSample--net7.0-S1186.json
  analyzers/its/expected/BlazorSample/BlazorSample--net7.0-S1451.json
  analyzers/its/expected/BlazorSample/BlazorSample--net7.0-S2333.json
  analyzers/its/expected/BlazorSample/BlazorSample--net7.0-S2339.json
  analyzers/its/expected/BlazorSample/BlazorSample--net7.0-S6798.json
  analyzers/its/expected/BlazorSample/BlazorSample--net7.0-S6800.json
  analyzers/its/sources/BlazorSample/BlazorSample/Pages/S6798/S6798.CSharpOnly.cs
  analyzers/its/sources/BlazorSample/BlazorSample/Pages/S6798/S6798.Partial.razor
  analyzers/its/sources/BlazorSample/BlazorSample/Pages/S6798/S6798.Partial.razor.cs
  analyzers/its/sources/BlazorSample/BlazorSample/Pages/S6798/S6798.razor
  analyzers/its/sources/BlazorSample/BlazorSample/Pages/S6800/Constants.cs
  analyzers/its/sources/BlazorSample/BlazorSample/Pages/S6800/S6800.razor
  analyzers/its/sources/BlazorSample/BlazorSample/Pages/S6800/S6800CsharpOnly.cs
  analyzers/its/sources/BlazorSample/BlazorSample/Pages/S6800/S6800Partial.razor
  its/projects/RazorClassLib/S6798/S6798.CSharpOnly.cs
  its/projects/RazorClassLib/S6798/S6798.Partial.razor
  its/projects/RazorClassLib/S6798/S6798.Partial.razor.cs
  its/projects/RazorClassLib/S6798/S6798.razor
  its/projects/RazorClassLib/S6800/Constants.cs
  its/projects/RazorClassLib/S6800/S6800.CsharpOnly.cs
  its/projects/RazorClassLib/S6800/S6800.Partial.razor
  its/projects/RazorClassLib/S6800/S6800.razor
  its/src/test/java/com/sonar/it/csharp/RazorClassLibProjectTest.java
Labels: Sprint: MMF-3457

#8387 Fix S6802 FP: Reduce scope to raise only within loop blocks
  analyzers/rspec/cs/S6802.html
  analyzers/rspec/cs/Sonar_way_profile.json
  analyzers/src/SonarAnalyzer.CSharp/Rules/AvoidLambdaExpressionInLoopsInBlazor.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/AvoidLambdaExpressionInLoopsInBlazorTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AvoidLambdaExpressionInLoopsInBlazor.LoopsWithNoBody.razor
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AvoidLambdaExpressionInLoopsInBlazor.RenderFragmentConsumer.razor
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AvoidLambdaExpressionInLoopsInBlazor.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/AvoidLambdaExpressionInLoopsInBlazor.razor
  its/profiles/blazor_rules.xml
  its/src/test/java/com/sonar/it/csharp/RazorClassLibProjectTest.java
  its/src/test/java/com/sonar/it/csharp/Tests.java
Labels: Area: C#, Sprint: MMF-3457

#8385 NullPointerDereference.SyntaxKindWalker reduce allocations and evaluations in the hot path
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/NullPointerDereference.cs
  analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/NullPointerDereference.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/NullPointerDereferenceSyntaxKindWalkerTests.cs
Labels: Sprint: Performance

#8388 TokenTypeAnalyzer: Use heuristic for lowercase identifier
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/TokenTypeAnalyzerTest.Classifier.cs
Labels: Sprint: Performance

#8183 Improve S5443 performance: Reuse compiled Regex
  analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/PubliclyWritableDirectoriesBase.cs
Labels: Area: VB.NET, Area: C#, Type: Performance, Sprint: Performance

#8380 UtilityAnalyzer: Add RegisterSemanticModelAction() and tests
  analyzers/src/SonarAnalyzer.CSharp/Extensions/SonarAnalysisContextExtensions.cs
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCompilationStartAnalysisContext.cs
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarSemanticModelReportingContext.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/ReportingContext.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SonarAnalysisContextExtensions.cs
  analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.Register.cs
  analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarSemanticModelReportingContextTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/UtilityAnalyzerBaseTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/DummyAnalyzer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/TestAnalyzer.cs
Labels: Sprint: Performance

#8185 Improve S2068 performance: Reuse compiled Regex
  analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/DoNotHardcodeCredentialsBase.cs
Labels: Area: VB.NET, Area: C#, Type: Performance, Sprint: Performance

#8396 Remove HasMatchingScope from Execute for SyntaxNode
  analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/ClearTextProtocolsAreSensitive.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/DisablingCsrfProtection.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/PermissiveCors.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/JSInvokableMethodsShouldBePublic.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/UseStringCreate.cs
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContext.cs
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarCompilationStartAnalysisContext.cs
  analyzers/src/SonarAnalyzer.Common/Rules/DateAndTimeShouldNotBeUsedasTypeForPrimaryKeyBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/DoNotCallMethodsBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/UseUnixEpochBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.Register.cs
Labels: Type: Improvement, Type: Performance, Sprint: Performance

#8410 S3415, S2701, S2699, S2187: Fix failing tests for NUnit 4.0 release
  analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/AssertionArgsShouldBePassedInCorrectOrderTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/DoNotUseLiteralBoolInAssertionsTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/TestClassShouldHaveTestMethodTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/TestMethodShouldContainAssertionTest.cs
Labels: Area: C#

#7036 S1905: Use NullableAnnotation() to find differences in type annotations
  analyzers/src/SonarAnalyzer.CFG/ShimLayer/ISymbolNullableExtensions.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/RedundantCast.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Wrappers/ISymbolNullableExtensionsTest.cs
Labels: Type: Improvement, Area: VB.NET, Area: C#
