Repository SonarSource/sonar-dotnet, pull requests merged in 2023-06, with the labels that each got.

#7318 Improve S2437: message - replace silly with unnecessary
  analyzers/its/expected/Net5/Net5--net5.0-S2437.json
  analyzers/src/SonarAnalyzer.CSharp/Rules/UnnecessaryBitwiseOperation.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/UnnecessaryBitwiseOperationCodeFix.cs
  analyzers/src/SonarAnalyzer.Common/Rules/UnnecessaryBitwiseOperationBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/UnnecessaryBitwiseOperationCodeFixBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/UnnecessaryBitwiseOperation.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/UnnecessaryBitwiseOperationCodeFix.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnnecessaryBitwiseOperationTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryBitwiseOperation.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryBitwiseOperation.Fixed.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryBitwiseOperation.Fixed.vb
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryBitwiseOperation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryBitwiseOperation.vb
Labels: Type: Improvement, Area: VB.NET, Area: C#

#7310 SE: Improve XOROperation
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Arithmetic.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
Labels: Sprint: SE

#7306 Migrate S1944: Scaffold the rule for the new SE
  analyzers/src/SonarAnalyzer.CSharp/Rules/InvalidCastToInterface.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/InvalidCastToInterface.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Analyzers/InvalidCastToInterfaceSymbolicExecution.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/InvalidCastToInterfaceBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/InvalidCastToInterfaceTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InvalidCastToInterface.CSharp10.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InvalidCastToInterface.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InvalidCastToInterface.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/InvalidCastToInterface.cs
Labels: Sprint: SE

#7315 Migrate S3966: Scaffold the rule for the new SE
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ObjectsShouldNotBeDisposedMoreThanOnceBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnceTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
Labels: Sprint: SE

#7246 SE: Add BitXorOperation
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Arithmetic.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.vb
Labels: Sprint: SE

#7341 Migrate S4158: Scaffold the rule for the new SE
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumeratedTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp10.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp11.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/EmptyCollectionsShouldNotBeEnumerated.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/EmptyCollectionsShouldNotBeEnumerated.cs
Labels: Sprint: SE

#7352 SE: Add SymbolicContext.SetOperationValue
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/ConstantCheck.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CompoundAssignment.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Conversion.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ObjectCreation.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
Labels: Sprint: SE

#7353 SE: Refactor FlowCaptureReference to operation processor
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/FlowCapture.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationValue.cs
Labels: Sprint: SE

#7330 Migrate S3966: Implement rule logic
  analyzers/its/expected/akka.net/Akka--netstandard2.0-S3966.json
  analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Analyzers/ObjectsShouldNotBeDisposedMoreThanOnce.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ConstraintKind.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/DisposableConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ObjectsShouldNotBeDisposedMoreThanOnceBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnceTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp10.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
Labels: Sprint: SE

#7365 Improve S2198: message - replace silly with unnecessary
  analyzers/src/SonarAnalyzer.CSharp/Rules/UnnecessaryMathematicalComparison.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/UnnecessaryMathematicalComparison.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/NameOfShouldBeUsed.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryMathematicalComparison.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UnnecessaryMathematicalComparison.cs
Labels: Type: Improvement, Area: C#

#7343 Migrate S4158: Implement rule logic
  analyzers/its/expected/Automapper/AutoMapper--net461-S4158.json
  analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S4158.json
  analyzers/its/expected/Nancy/Nancy--net452-S4158.json
  analyzers/its/expected/Nancy/Nancy--netstandard2.0-S4158.json
  analyzers/its/expected/Nancy/Nancy.Testing--net452-S4158.json
  analyzers/its/expected/Nancy/Nancy.Testing--netstandard2.0-S4158.json
  analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S4158.json
  analyzers/its/expected/akka.net/Akka.Cluster.Sharding--netstandard2.0-S4158.json
  analyzers/its/expected/akka.net/Akka.DistributedData--netstandard2.0-S4158.json
  analyzers/its/expected/akka.net/Akka.Persistence--netstandard2.0-S4158.json
  analyzers/its/expected/akka.net/Akka.Persistence.Sql.Common--netstandard2.0-S4158.json
  analyzers/its/expected/akka.net/Akka.Streams.TestKit--netstandard2.0-S4158.json
  analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S4158.json
  analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/CollectionConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyCollectionsShouldNotBeEnumeratedTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
Labels: Sprint: SE

#7366 Migrate S4158: Support Array Creation
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
Labels: Sprint: SE

#7367 Migrate S4158: Support Constructor with Enumerable
  analyzers/its/expected/akka.net/Akka.Cluster.Sharding--netstandard2.0-S4158.json
  analyzers/its/expected/akka.net/Akka.Persistence--netstandard2.0-S4158.json
  analyzers/its/expected/akka.net/Akka.Streams.TestKit--netstandard2.0-S4158.json
  analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S4158.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Argument.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
Labels: Sprint: SE

#7431 Fix S3966: AD0001 when inspecting Dispose that is not invoked from an instance.
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/KnownMethods.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/ObjectsShouldNotBeDisposedMoreThanOnceBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
Labels: Sprint: SE

#7417 Migrate S4158: Support Object Initializers
  analyzers/its/expected/Nancy/Nancy--net452-S4158.json
  analyzers/its/expected/Nancy/Nancy--netstandard2.0-S4158.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
Labels: Sprint: SE

#7448 Migrate S4158: Implement ShouldExecute
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.vb
Labels: Sprint: SE

#7418 Migrate S4158: Support Dictionary Setter
  analyzers/its/expected/Nancy/Nancy--net452-S4158.json
  analyzers/its/expected/Nancy/Nancy--netstandard2.0-S4158.json
  analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S4158.json
  analyzers/its/expected/akka.net/Akka.DistributedData--netstandard2.0-S4158.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.CaptureOperation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
Labels: Sprint: SE

#7433 Migrate S4158: Passing as argument removes constraint
  analyzers/its/expected/Automapper/AutoMapper--net461-S4158.json
  analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S4158.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.InvocationAttribute.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicValueTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.vb
Labels: Sprint: SE

#7453 Migrate S4158: Do not report on method references
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
Labels: Sprint: SE

#7435 Update message of S4635
  analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/IntentionalFindings/S4635.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/StringOffsetMethods.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringOffsetMethods.CSharp11.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/StringOffsetMethods.cs
Labels: Area: C#

#7459 Minor improvements for S4158
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
Labels: Sprint: SE

#7458 VB.NET HasExactlyNArguments method considers null argument list and 0 arguments the same.
  analyzers/src/SonarAnalyzer.VisualBasic/Extensions/InvocationExpressionSyntaxExtensions.cs
  analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
Labels: Type: Improvement, Area: VB.NET

#7486 Improve S6640: Support type declarations
  analyzers/its/expected/Net5/Net5--net5.0-S6640.json
  analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/UnsafeCodeBlocks.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Hotspots/UnsafeCodeBlocksTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/UnsafeCodeBlocks.cs
Labels: Sprint: MMF-3253

#7481 Improve S6640: Support local functions
  analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/UnsafeCodeBlocks.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/UnsafeCodeBlocks.cs
Labels: Sprint: MMF-3253

#7492 Improve S6640: Support fields, properties and delegates
  analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/UnsafeCodeBlocks.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/UnsafeCodeBlocks.cs
Labels: Sprint: MMF-3253

#7499 S3966: Add FP repro for #7497
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ObjectsShouldNotBeDisposedMoreThanOnce.cs
Labels: Area: C#

#7471 New Rule S3363: C# implementation
  analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/IntentionalFindings/IntentionalFindings.csproj
  analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/IntentionalFindings/S3363.cs
  analyzers/rspec/cs/S3363.html
  analyzers/rspec/cs/S3363.json
  analyzers/rspec/cs/Sonar_way_profile.json
  analyzers/src/SonarAnalyzer.CSharp/Helpers/CSharpSyntaxHelper.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/DateAndTimeShouldNotBeUsedasTypeForPrimaryKey.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Helpers/VisualBasicSyntaxHelper.cs
  analyzers/tests/SonarAnalyzer.UnitTest/MetadataReferences/NuGetMetadataReference.cs
  analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeMappingCS.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/DateAndTimeShouldNotBeUsedasTypeForPrimaryKeyTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DateAndTimeShouldNotBeUsedasTypeForPrimaryKey.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DateAndTimeShouldNotBeUsedasTypeForPrimaryKey.EntityFrameworkCore.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DateAndTimeShouldNotBeUsedasTypeForPrimaryKey.FluentApi.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DateAndTimeShouldNotBeUsedasTypeForPrimaryKey.NoReferenceToEntityFramework.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/DateAndTimeShouldNotBeUsedasTypeForPrimaryKey.cs
Labels: Sprint: MMF-3068

#7510 S5332 Fix AD0001 because of unsupported ConstructorInitializerSyntax
  analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpFacade.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Hotspots/ClearTextProtocolsAreSensitive.cs
Labels: Type: Bug, Area: C#

#7506 Improve IsNameOf to check syntax before semantic model
  analyzers/src/SonarAnalyzer.CFG/Helpers/CSharpSyntaxHelper.cs
Labels: Type: Improvement, Area: VB.NET, Area: C#
