Repository SonarSource/sonar-dotnet, pull requests merged in 2023-10, with the labels that each got.

#8180 Add Collection Expression syntax to the ShimLayer
  analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml
Labels: Sprint: MMF-3410

#8182 Add Alias any Type syntax to the ShimLayer
  analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml
Labels: Sprint: MMF-3410

#8184 Add Primary Constructor syntax to the ShimLayer
  analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml
Labels: Sprint: MMF-3410

#8146 Fix S1075 FN: default parameters
  analyzers/src/SonarAnalyzer.CSharp/Extensions/ArgumentSyntaxExtensions.cs
  analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/UriShouldNotBeHardcoded.cs
  analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
  analyzers/src/SonarAnalyzer.Common/Rules/UriShouldNotBeHardcodedBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Extensions/ArgumentSyntaxExtensions.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SyntaxNodeExtensions.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/UriShouldNotBeHardcoded.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp11.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp12.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.vb
Labels: Sprint: MMF-3410

#7877 Fix S4158 FN: Learn Constraint from Count
  analyzers/its/expected/akka.net/Akka.Cluster.Sharding--netstandard2.0-S2583.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/CollectionConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Collections.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.vb
Labels: Type: False Negative, Area: CFG/SE, Area: VB.NET, Area: C#

#8201 Update ShimLayer: sync with Roslyn's Syntax.xml
  analyzers/src/SonarAnalyzer.CFG/ShimLayer/Syntax.xml
  analyzers/src/SonarAnalyzer.CFG/ShimLayer/TypeDeclarationExtensions.cs
  analyzers/src/SonarAnalyzer.ShimLayer.CodeGeneration/SyntaxLightupGenerator.cs
Labels: Sprint: MMF-3410

#8210 Update ShimLayer: sync with Roslyn's Syntax.xml fix
  analyzers/src/SonarAnalyzer.CFG/ShimLayer/TypeDeclarationExtensions.cs
Labels: Sprint: MMF-3410

#8189 Move LiteralText to the SyntaxFacade
  analyzers/src/SonarAnalyzer.CSharp/Extensions/ArgumentSyntaxExtensions.cs
  analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/Hotspots/HardcodedIpAddress.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/InsecureEncryptionAlgorithm.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/UriShouldNotBeHardcoded.cs
  analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
  analyzers/src/SonarAnalyzer.Common/Rules/DoNotCallInsecureSecurityAlgorithmBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Hotspots/HardcodedIpAddressBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/UriShouldNotBeHardcodedBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Extensions/ArgumentSyntaxExtensions.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/Hotspots/HardcodedIpAddress.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/InsecureEncryptionAlgorithm.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/UriShouldNotBeHardcoded.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp11.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.CSharp12.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/UriShouldNotBeHardcoded.vb
Labels: Sprint: MMF-3410

#8208 Fix S2583/S2589 FP: Not tracked collection types can learn `CollectionConstraint` from `BinaryOperation`
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Collections.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/CollectionConstraintTests.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
Labels: Area: CFG/SE, Area: VB.NET, Area: C#, Type: CFG/SE FPs

#8158 .NET 8 and C# 12: add repros and UTs for .NET 8-only features
  analyzers/tests/SonarAnalyzer.Net8.UnitTest/Rules/BypassingAccessibilityTest.cs
  analyzers/tests/SonarAnalyzer.Net8.UnitTest/Rules/PublicMethodWithMultidimensionalArrayTest.cs
  analyzers/tests/SonarAnalyzer.Net8.UnitTest/Rules/SecurityPInvokeMethodShouldNotBeCalledTest.cs
  analyzers/tests/SonarAnalyzer.Net8.UnitTest/Rules/SelfAssignmentTest.cs
  analyzers/tests/SonarAnalyzer.Net8.UnitTest/Rules/TooManyParametersTest.cs
  analyzers/tests/SonarAnalyzer.Net8.UnitTest/TestCases/BypassingAccessibility.cs
  analyzers/tests/SonarAnalyzer.Net8.UnitTest/TestCases/PublicMethodWithMultidimensionalArray.cs
  analyzers/tests/SonarAnalyzer.Net8.UnitTest/TestCases/SecurityPInvokeMethodShouldNotBeCalled.cs
  analyzers/tests/SonarAnalyzer.Net8.UnitTest/TestCases/SelfAssignment.cs
  analyzers/tests/SonarAnalyzer.Net8.UnitTest/TestCases/TooManyParameters_CustomValues.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/PublicMethodWithMultidimensionalArrayTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SelfAssignmentTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/TooManyParametersTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SelfAssignment.CSharp12.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/TooManyParameters_CustomValues.CSharp12.cs
Labels: Sprint: MMF-3410

#8259 S3247: Add repro for #223
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CastShouldNotBeDuplicated.CSharp12.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CastShouldNotBeDuplicated.cs
Labels: Sprint: MMF-3410

#8268 Repo for S2583 FP: Code wrongly considered unreachable
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
Labels: Type: False Positive, Area: CFG/SE, Area: C#
