Repository SonarSource/sonar-dotnet, pull requests merged in 2023-04, with the labels that each got.

#7021 Fix S2259 FP: IsType returns false for Null values
  analyzers/its/expected/akka.net/Akka.Remote--netstandard2.0-S2259.json
  analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S2259.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Labels: Sprint: SE

#6994 S2222: Branch on createdNew parameter on Mutex constructor
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/LocksReleasedAllPathsBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/IOperationExtensionsTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Mutex.NetFx.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/LocksReleasedAllPaths.Mutex.cs
Labels: Sprint: SE

#7018 S3900: Fix issue message for constructors
  analyzers/its/expected/Automapper/AutoMapper--net461-S3900.json
  analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S3900.json
  analyzers/its/expected/Nancy/Nancy--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy--netstandard2.0-S3900.json
  analyzers/its/expected/Nancy/Nancy.Demo.Hosting.Kestrel--netcoreapp2.0-S3900.json
  analyzers/its/expected/Nancy/Nancy.Hosting.Self--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy.Hosting.Self--netstandard2.0-S3900.json
  analyzers/its/expected/Nancy/Nancy.Testing--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy.Testing--netstandard2.0-S3900.json
  analyzers/its/expected/Nancy/Nancy.Validation.DataAnnotations--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy.ViewEngines.Spark--net452-S3900.json
  analyzers/its/expected/akka.net/Akka--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Cluster.Metrics--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Cluster.Tools--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Discovery--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.DistributedData--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.DistributedData.LightningDB--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Persistence--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Persistence.Query.Sql--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Persistence.Sql.Common--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Persistence.Sqlite--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Remote--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Remote.TestKit--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Serialization.Hyperion--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Serialization.TestKit--net471-S3900.json
  analyzers/its/expected/akka.net/Akka.Serialization.TestKit--net5.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Serialization.TestKit--netcoreapp3.1-S3900.json
  analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S3900.json
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
Labels: Sprint: SE

#7006 S3655: "In" method params
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyNullableValueAccessTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.NullableContext.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
Labels: Sprint: SE

#7037 SE: Use Nullable<int> instead of Lazy<int> for HashCode caching in old SE
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/ExplodedGraphNode.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/ProgramPoint.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/ProgramState.cs
Labels: Sprint: SE

#7030 S3655: Add non-compliance to ITs in intentional findings
  analyzers/its/sources/ManuallyAddedNoncompliantIssues.CS/IntentionalFindings/S3655.cs
Labels: Sprint: SE

#7023 Fix S3900 FP: After coalesce with assignment.
  analyzers/its/expected/akka.net/Akka.Persistence.Query.Sql--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Persistence.TestKit--netstandard2.0-S2259.json
  analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S3900.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ExceptionCandidate.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IsNull.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
Labels: Sprint: SE

#7033 S3655: Document comparisons
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
Labels: Sprint: SE

#7051 SE: Fix test case IsNull_CoalesceAssignment_UnknownToNotNull
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.IsNull.cs
Labels: Sprint: SE

#7046 S3900: Add FP repro for captured parameters
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
Labels: Sprint: SE

#7022 SE: Precision: Fix missing NotNull constraint in RoslynSymbolicExecution.SetBranchingConstraints
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ExplodedNode.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
  azure-pipelines.yml
Labels: Sprint: SE

#7029 S3655: Null conditional operator, null coalescing assignment, value tuples
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
Labels: Sprint: SE

#7052 S2259: Add FP reproducers from Peach
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Labels: Sprint: SE

#7062 FP S4462: Re-producer for #7053 (Result is accessed after Task.WhenAll)
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/CallToAsyncMethodShouldNotBeBlocking.cs
Labels: Type: False Positive, Area: C#

#7070 RoslynCfgSerializer: Do not render syntax type
  analyzers/src/SonarAnalyzer.CFG/Extensions/IOperationExtensions.cs
  analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/RoslynCfgSerializerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ExplodedNodeTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
Labels: Sprint: SE

#7041 S3655: RSPEC update and test fixes
  analyzers/rspec/cs/S3655_c#.html
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.vb
Labels: Sprint: SE

#7065 SE: S3900 FP: Don't raise if parameter is captured
  analyzers/its/expected/Automapper/AutoMapper--net461-S3900.json
  analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S3900.json
  analyzers/its/expected/Ember-MM/generic.EmberCore.NMT-{84B2143A-D04F-4262-923D-21AEDF86E2B7}-S3900.json
  analyzers/its/expected/Ember-MM/scraper.EmberCore.XML-{E567C031-1F7B-4637-9B3A-806988DE50CF}-S3900.json
  analyzers/its/expected/Nancy/Nancy--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy--netstandard2.0-S3900.json
  analyzers/its/expected/Nancy/Nancy.Embedded--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy.Embedded--netstandard2.0-S3900.json
  analyzers/its/expected/Nancy/Nancy.Testing--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy.Testing--netstandard2.0-S3900.json
  analyzers/its/expected/Nancy/Nancy.ViewEngines.DotLiquid--net452-S3900.json
  analyzers/its/expected/akka.net/Akka--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Cluster.Sharding--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Discovery--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Persistence--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Persistence.Sql.Common--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Serialization.Hyperion--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Streams.TestKit--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S3900.json
  analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/LiveVariableAnalysisBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/PublicMethodArgumentsShouldBeCheckedForNullBase.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicCheckListTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.vb
Labels: Sprint: SE

#7015 S3655: Honor null forgiving operator
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyNullableValueAccessBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.NullableContext.cs
Labels: Sprint: SE

#7054 SE: Don't branch on relational operator against null
  analyzers/src/SonarAnalyzer.Common/Extensions/BinaryOperatorKindExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs
Labels: Sprint: SE

#7055 SE: Learn NotNull on relational operator on nullable value types
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
Labels: Sprint: SE

#7044 Fix S3900 FP: assigned parameters
  analyzers/its/expected/Automapper/AutoMapper--net461-S3900.json
  analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S3900.json
  analyzers/its/expected/Ember-MM/Ember Media Manager-{9B57D3AB-AF12-4012-B945-284C2448DC81}-S3900.json
  analyzers/its/expected/Ember-MM/Ember.Plugins-{9496C697-5AFD-4813-AEDC-AF33FACEADF0}-S3900.json
  analyzers/its/expected/Ember-MM/EmberAPI-{208AA35E-C6AE-4D2D-A9DD-B6EFD19A4279}-S3900.json
  analyzers/its/expected/Ember-MM/generic.EmberCore.XBMC-{6FE33C61-E2C2-4982-9536-63AEF0A98AAA}-S3900.json
  analyzers/its/expected/Ember-MM/scraper.EmberCore.XML-{E567C031-1F7B-4637-9B3A-806988DE50CF}-S3900.json
  analyzers/its/expected/Nancy/Nancy--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Cluster.TestKit--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Remote.TestKit--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S3900.json
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ConstraintKind.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ParameterReassignedConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/PublicMethodArgumentsShouldBeCheckedForNullBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ParameterReassignedConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SymbolicConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.vb
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
Labels: Sprint: SE

#7090 Add reproducer for #7088
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/ConditionEvaluatesToConstant.CSharp8.cs
Labels: Type: False Positive, Area: CFG/SE, Area: C#

#7118 Update SonarLint
  analyzers/.sonarlint/SonarAnalyzer.slconfig
  analyzers/.sonarlint/sonaranalyzer-dotnetCSharp.ruleset
  analyzers/.sonarlint/sonaranalyzer-dotnet_secrets_settings.json
Labels: Type: Improvement
