Repository SonarSource/sonar-dotnet, pull requests merged in 2023-03, with the labels that each got.

#6785 Performance: Token Type Utility Analyzer: Avoid allocations
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/TokenTypeAnalyzer.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/Utilities/TokenTypeAnalyzer.cs
Labels: Sprint: Hardening

#6627 Packages: Upgrade FluentAssertions
  analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/BasicBlockTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/CaptureIdTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/CFG/Sonar/SonarControlFlowGraphTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Common/BidirectionalDictionaryTests.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Common/DistrubtionTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/DiagnosticDescriptorFactoryTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/MethodParameterLookupTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/OperationExecutionOrderTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SymbolHelperTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Json/JsonWalkerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ExplodedNodeTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SonarExplodedGraphTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SymbolicValues/NullableSymbolicValue_TrySetConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SymbolicValues/NullableSymbolicValue_TrySetOppositeConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SymbolicValues/SymbolicValue_TrySetConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/FluentTestHelper.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/ValidatorTestCheck.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/IssueLocationCollectorTest.GetExpectedIssueLocations.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/IssueLocationCollectorTest.GetIssueLocations.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/ParseOptionsHelperTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/VerifierBuilderTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestSuiteInitialization.cs
  analyzers/tests/SonarAnalyzer.UnitTest/packages.lock.json
Labels: Sprint: Hardening

#6838 SyntaxFacade: fix the order of parameters in IsKnownAttributeType
  analyzers/src/SonarAnalyzer.CSharp/Facade/CSharpSyntaxFacade.cs
  analyzers/src/SonarAnalyzer.Common/Facade/SyntaxFacade.cs
  analyzers/src/SonarAnalyzer.Common/Rules/DebuggerDisplayUsesExistingMembersBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Facade/VisualBasicSyntaxFacade.cs
Labels: Type: Improvement

#6841 SE - Nullable: Copy constraints to `Value` property
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
Labels: Sprint: SE

#6854 New rule S6507: Blocks should not be synchronized on local variables
  analyzers/its/expected/Automapper/AutoMapper--net461-S6507.json
  analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S6507.json
  analyzers/rspec/cs/S2445_c#.html
  analyzers/rspec/cs/S6507_c#.html
  analyzers/rspec/cs/S6507_c#.json
  analyzers/src/SonarAnalyzer.CSharp/Rules/LockedFieldShouldBeReadonly.cs
  analyzers/tests/SonarAnalyzer.UnitTest/PackagingTests/RuleTypeMappingCS.cs
Labels: Area: C#, Type: New Rule, Sprint: MMF-2910

#6148 SE: Add ConstraintKind
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Constraints/ByteArrayConstraint.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Constraints/CollectionConstraint.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Constraints/DisposableConstraint.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Constraints/InitializationVectorConstraint.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Constraints/NullableConstraint.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Constraints/SaltSizeConstraint.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Constraints/SerializationConstraint.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Sonar/Constraints/StringConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/BoolConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ConstraintKind.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/LockConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Constraints/ObjectConstraint.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/SymbolicConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicValueTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/Constraints/ByteArrayConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/Constraints/InitializationVectorConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/Constraints/SaltSizeConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/Constraints/SerializationConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Sonar/SonarProgramStateTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/SymbolicConstraintTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/TestConstraints.cs
Labels: Type: Improvement, Area: CFG/SE, Sprint: SE

#6853 SE - Nullable: Add `Null` constraint for empty nullable constructor
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ObjectCreation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
Labels: Sprint: SE

#6844 S3655: Prepare TestCases
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.CSharp10.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.CSharp11.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
Labels: Sprint: SE

#6881 SE: Serialize Captures with prefix
  analyzers/src/SonarAnalyzer.CFG/CfgSerializer/CfgSerializer.RoslynCfgWalker.cs
  analyzers/src/SonarAnalyzer.CFG/Extensions/IOperationExtensions.cs
  analyzers/src/SonarAnalyzer.CFG/ShimLayer/CaptureId.cs
  analyzers/tests/SonarAnalyzer.UnitTest/CFG/Roslyn/RoslynCfgSerializerTest.cs
Labels: Sprint: SE

#6856 SE - Nullable: Propagate constraints via nullable constructor
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ObjectCreation.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
Labels: Sprint: SE

#6857 SE - Nullable: Add UT for conversions
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Conversion.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
Labels: Sprint: SE

#6872 SE - Nullable: Change `PropertyReference` to branching processor
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Assignment.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/BranchingProcessor.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsNull.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsType.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationValue.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
Labels: Sprint: SE

#6034 Add SymbolicValueAssertions
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.SymbolValue.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SymbolicValueAssertions.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/SymbolicValueAssertionsTest.cs
Labels: Sprint: SE

#6864 SE - Non-nullable value types: Add NonNullableValueTypeCheck
  analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/NonNullableValueTypeCheck.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.InvocationAttribute.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.PatternMatching.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
Labels: Sprint: SE

#6879 SE - Non-nullable value types: Keep NotNull constraint in branching
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
Labels: Sprint: SE

#6876 S3655: Scaffold rule and UTs
  analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyNullableValueAccessTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
Labels: Sprint: SE

#6882 SE - Nullable: Learn `ObjectConstraint` from branching on `nullable.HasValue`
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
Labels: Sprint: SE

#6891 UTs: Cleanup ResourceTest folder
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/ParameterLoaderTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarLintXmlReaderTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarLintXmlTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/AnalyzeGeneratedFalse/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/AnalyzeGeneratedFalseVbnet/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/AnalyzeGeneratedTrue/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/AnalyzeGeneratedTrueVbnet/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/IgnoreHeaderCommentsFalseCSharp/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/IgnoreHeaderCommentsFalseVbnet/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/IgnoreHeaderCommentsTrueCSharp/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/IgnoreHeaderCommentsTrueVbnet/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/SonarLintXml/All_properties_cs/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/SonarLintXml/All_properties_small_template/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/SonarLintXml/All_properties_vbnet/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/SonarLintXml/RuleWithBooleanParameter/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/SonarLintXml/RuleWithStringParameter/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/SonarLintXml/StringInsteadOfBoolean/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/SonarLintXml/StringInsteadOfInt/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/ToChange/SonarLint.xml
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/UtilityAnalyzerBaseTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/AnalysisScaffolding.cs
Labels: Sprint: SonarLint

#6928 Fix S6513: VB test failures
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ExcludeFromCodeCoverageAttributesNeedJustification.vb
Labels: Type: Improvement, Area: VB.NET

#6927 Fix SL feature branch ITs
  analyzers/its/expected/SonarLintExclusions/SonarLintExclusions--net7.0-S1451.json
  analyzers/its/sources/AnalyzeGenerated.CS/SonarLint.xml
  analyzers/its/sources/SkipGenerated.CS/SonarLint.xml
Labels: Sprint: SonarLint

#6932 Fix SE: DictionaryContentHash is not stable to ordering
  analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/DictionaryExtensionsTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/HashCodeTest.cs
Labels: Sprint: SE

#6905 Remove language property from SonarLintXmlReader
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
  analyzers/src/SonarAnalyzer.Common/Common/UnexpectedLanguageException.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/SonarLintXmlReader.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextBaseTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Common/UnexpectedLanguageExceptionTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/SonarLintXmlReaderTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/ResourceTests/SonarLintXml/PropertiesCSharpTrueVbnetFalse/SonarLint.xml
Labels: Sprint: SonarLint

#6915 SonarAnalysisContextBase refactoring
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
  analyzers/src/SonarAnalyzer.Common/DiagnosticAnalyzer/ParametrizedDiagnosticAnalyzer.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/SonarLintXmlReader.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/AnalysisContext/SonarAnalysisContextBaseTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/ParameterLoaderTest.cs
Labels: Sprint: SonarLint

#6919 Wildcard pattern matcher improvement
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarAnalysisContextBase.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/WildcardPatternMatcher.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/WildcardPatternMatcherTest.cs
Labels: Sprint: SonarLint

#6931 SE - Property reference: Test case for auto properties are not learning constraints
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/SymbolicExecution/SETestContext.cs
Labels: Sprint: SE

#6925 SE - Nullable: Learn object constraint from value comparison
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
Labels: Sprint: SE

#6917 S3900: Dummy rule implementation
  analyzers/src/SonarAnalyzer.CSharp/Rules/SymbolicExecution/SymbolicExecutionRunner.cs
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/PublicMethodArgumentsShouldBeCheckedForNullTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/PublicMethodArgumentsShouldBeCheckedForNull.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/PublicMethodArgumentsShouldBeCheckedForNull.cs
Labels: Sprint: SE

#6949 SE - Non-nullable value types: Remove Enum constraint from IsStruct()
  analyzers/src/SonarAnalyzer.Common/Helpers/TypeHelper.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/TypeHelperTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
Labels: Sprint: SE

#6955 SE - Nullable: Learn NotNull from recursive pattern
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/IsPattern.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
Labels: Sprint: SE

#6913 SE - Add cache for SymbolicValues
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicValueTest.cs
Labels: Sprint: SE

#6918 S3655: Extend tests, fix ShouldExecute and FP on non-nullable value types
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Sonar/EmptyNullableValueAccess.cs
Labels: Sprint: SE

#6890 Fix S1123 FN: The explanation should not be null or whitespace
  analyzers/src/SonarAnalyzer.CSharp/Rules/ObsoleteAttributes.cs
  analyzers/src/SonarAnalyzer.Common/Rules/ObsoleteAttributesBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/ObsoleteAttributes.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/ObsoleteAttributesTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.VB14.vb
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.vb
Labels: Type: False Negative, Area: VB.NET, Area: C#

#6978 SE: Make SymbolicValue ctor private.
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ExplodedNodeTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.OperationValue.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.SymbolValue.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/ProgramStateTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicContextTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestFramework/Tests/SymbolicValueAssertionsTest.cs
Labels: Sprint: SE

#6980 SE: Maintenance: Remove SymbolicValue.This
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/References.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
Labels: Sprint: SE

#6982 SE: Maintenance: Unroll SymbolicCheckList.InvokeChecks
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicCheckList.cs
Labels: Sprint: SE

#6988 Fix syntax error in ObsoleteAttributesNeedExplanation_VB test case
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/ObsoleteAttributesNeedExplanation.vb
Labels: Area: VB.NET

#6956 SE - Nullable: Add UTs for Debug.Assert
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
Labels: Sprint: SE

#6979 SE: Enumerable ContentHash for ordered and unordered sets
  analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/ProgramState.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/HashCodeTest.cs
Labels: Sprint: SE

#6969 S3900: Basic rule implementation
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.CSharp11.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.CSharp8.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.CSharp9.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
Labels: Sprint: SE

#6968 SE: Caching: Cache "GetHashCode" for SymbolicValue
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicValue.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/SymbolicValueTest.cs
Labels: Sprint: SE

#6962 S3655: Deconstruction and null forgiving operator
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SymbolicExecution/EmptyNullableValueAccessTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.NullableContext.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
Labels: Sprint: SE

#6991 Fix S3655 FN: VB implicit conversions
  analyzers/src/SonarAnalyzer.VisualBasic/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.vb
Labels: Area: CFG/SE, Area: VB.NET, Sprint: SE

#6981 S3655: Fields with methods, local functions, yield and async
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyNullableValueAccess.cs
Labels: Sprint: SE

#6989 S3655: Use IsNonNullableValueType
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyNullableValueAccessBase.cs
Labels: Sprint: SE

#6995 SE - Non-nullable value types: Set NotNull Constraint for tracked Symbols in NonNullableValueTypeCheck
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Checks/NonNullableValueTypeCheck.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Constants.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.InvocationAttribute.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Nullable.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.cs
Labels: Sprint: SE

#7002 Fix S3900 FN: Conversion operations
  analyzers/its/expected/Automapper/AutoMapper--net461-S3900.json
  analyzers/its/expected/Automapper/AutoMapper--netstandard2.0-S3900.json
  analyzers/its/expected/Nancy/Nancy--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy--netstandard2.0-S3900.json
  analyzers/its/expected/Nancy/Nancy.Hosting.Aspnet--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy.Testing--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy.Testing--netstandard2.0-S3900.json
  analyzers/its/expected/Nancy/Nancy.Validation.DataAnnotations--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy.Validation.FluentValidation--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy.Validation.FluentValidation--netstandard2.0-S3900.json
  analyzers/its/expected/Net5/Net5--net5.0-S3900.json
  analyzers/its/expected/Net6/NullableReferenceTypesExample--net6.0-S3900.json
  analyzers/its/expected/akka.net/Akka--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Persistence--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Persistence.Sql.Common--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Persistence.TestKit--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Remote.TestKit--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Streams.TestKit--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Tests.Shared.Internals--netstandard2.0-S3900.json
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
Labels: Sprint: SE

#7005 SE: Support ReferenceEquals
  analyzers/its/expected/Ember-MM/Ember.Plugins-{9496C697-5AFD-4813-AEDC-AF33FACEADF0}-S3900.json
  analyzers/its/expected/Nancy/Nancy--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Cluster--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Cluster.Metrics--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Cluster.Sharding--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Cluster.Tools--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.DistributedData--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.MultiNodeTestRunner.Shared--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Persistence--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Persistence.Query--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Remote--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Remote.TestKit--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Serialization.TestKit--net471-S3900.json
  analyzers/its/expected/akka.net/Akka.Serialization.TestKit--net5.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Serialization.TestKit--netcoreapp3.1-S3900.json
  analyzers/its/expected/akka.net/Akka.Streams--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.TestKit--netstandard2.0-S3900.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
  analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
Labels: Sprint: SE

#7004 S3900: Change parameter dereference check to top-down
  analyzers/its/expected/Nancy/Nancy--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy--netstandard2.0-S3900.json
  analyzers/its/expected/Nancy/Nancy.ViewEngines.Markdown--net452-S3900.json
  analyzers/its/expected/Nancy/Nancy.ViewEngines.Markdown--netstandard2.0-S3900.json
  analyzers/its/expected/akka.net/Akka.Tests.Shared.Internals--netstandard2.0-S3900.json
  analyzers/src/SonarAnalyzer.CSharp/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/PublicMethodArgumentsShouldBeCheckedForNull.cs
Labels: Sprint: SE

#7012 SE: Maintenance: Allocation free hash code implementation for immutable dict
  analyzers/src/SonarAnalyzer.Common/Helpers/HashCode.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Helpers/HashCodeTest.cs
Labels: Sprint: SE
