Repository SonarSource/sonar-dotnet, pull requests merged in 2023-09, with the labels that each got.

#7941 SE: Fix S4158 FP: Interfaces are only half tracked
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
Labels: Sprint: SE

#7915 Compute executable lines of code metric: UTs and first implementation
  analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpExecutableLinesMetric.cs
  analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpMetrics.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/DiagnosticReportHelper.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/GeneratedCodeRecognizer.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Metrics/CSharpExecutableLinesMetricTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
  sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/protobuf/RoslynMetricsImporterTest.java
  sonar-dotnet-shared-library/src/test/resources/RazorProtobufImporter/file-metadata.pb
  sonar-dotnet-shared-library/src/test/resources/RazorProtobufImporter/log.pb
  sonar-dotnet-shared-library/src/test/resources/RazorProtobufImporter/metrics.pb
  sonar-dotnet-shared-library/src/test/resources/RazorProtobufImporter/token-type.pb
Labels: Sprint: MMF-3322 🪒

#7916 Symbol reference: Implement location mapping for razor files
  analyzers/src/SonarAnalyzer.Common/Extensions/LocationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/SymbolReferenceAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/SymbolReferenceAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/SymbolReferenceAnalyzer/Razor.razor
  its/projects/RazorMetrics/Cases.razor
  its/src/test/java/com/sonar/it/csharp/RazorMetricsTest.java
  sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SensorContextUtils.java
  sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/CPDTokensImporter.java
  sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/HighlightImporter.java
  sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/SymbolRefsImporter.java
  sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/protobuf/RoslynMetricsImporterTest.java
  sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/protobuf/RoslynSymbolRefsImporterTest.java
  sonar-dotnet-shared-library/src/test/java/org/sonarsource/dotnet/shared/plugins/testutils/ProtobufFilterTool.java
  sonar-dotnet-shared-library/src/test/resources/RazorProtobufImporter/Cases.razor
  sonar-dotnet-shared-library/src/test/resources/RazorProtobufImporter/file-metadata.pb
  sonar-dotnet-shared-library/src/test/resources/RazorProtobufImporter/log.pb
  sonar-dotnet-shared-library/src/test/resources/RazorProtobufImporter/metrics.pb
  sonar-dotnet-shared-library/src/test/resources/RazorProtobufImporter/symrefs.pb
  sonar-dotnet-shared-library/src/test/resources/RazorProtobufImporter/token-cpd.pb
  sonar-dotnet-shared-library/src/test/resources/RazorProtobufImporter/token-type.pb
Labels: Sprint: MMF-3322 🪒

#7965 Rename parameter names to match our convention
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/CopyPasteTokenAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/FileMetadataAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/LogAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/MetricsAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/SymbolReferenceAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/TokenTypeAnalyzerBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/Utilities/UtilityAnalyzerBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/FileMetadataAnalyzerTest.cs
Labels: Sprint: MMF-3322 🪒

#7977 Add executable lines test coverage and solve peach validation issue
  analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpExecutableLinesMetric.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/MetricsAnalyzer/Component.razor
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/MetricsAnalyzer/Razor.razor
Labels: Sprint: MMF-3322 🪒

#7979 .razor: class count, ignore generated classes
  analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpMetrics.cs
  analyzers/src/SonarAnalyzer.Common/Metrics/MetricsBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/MetricsAnalyzer/Razor.razor
Labels: Sprint: MMF-3322 🪒

#7981 .razor: statement count, consider only mapped statements
  analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpMetrics.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
Labels: Sprint: MMF-3322 🪒

#7980 .razor: functions count, ignore generated function
  analyzers/src/SonarAnalyzer.CSharp/Metrics/CSharpMetrics.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
Labels: Sprint: MMF-3322 🪒

#7986 Razor cleanup
  analyzers/src/SonarAnalyzer.CSharp/Rules/Utilities/MetricsAnalyzer.cs
  analyzers/src/SonarAnalyzer.Common/Metrics/MetricsBase.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Common/MetricsTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
Labels: Sprint: MMF-3322 🪒

#8000 Document metric issues found during validation
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/Utilities/MetricsAnalyzerTest.cs
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/Utilities/MetricsAnalyzer/Razor.razor
Labels: Sprint: MMF-3322 🪒

#8015 S3427: Implement location fix for issues in razor files
  analyzers/src/SonarAnalyzer.CSharp/Rules/MethodOverloadOptionalParameter.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/MethodOverloadOptionalParameterTest.cs
Labels: Area: C#, Sprint: MMF-3322 🪒

#8014 S2589: Add repros
  analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.CSharp9.cs
Labels: Area: C#

#8017 S122 razor FN reproducer
  analyzers/src/SonarAnalyzer.CSharp/Rules/SingleStatementPerLine.cs
  analyzers/src/SonarAnalyzer.Common/Rules/SingleStatementPerLineBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/SingleStatementPerLine.cs
  analyzers/tests/SonarAnalyzer.UnitTest/Rules/SingleStatementPerLineTest.cs
Labels: Type: False Negative
