Repository SonarSource/sonar-dotnet, pull requests merged in 2024-04, with the labels that each got.

#9019 Fix S2094 FP: Primary constructors for classes should be handled equal to records
  analyzers/src/SonarAnalyzer.CSharp/Rules/ClassShouldNotBeEmpty.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/ClassShouldNotBeEmptyTest.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/ClassShouldNotBeEmpty.CSharp12.cs
Labels: Type: False Positive, Area: C#

#9049 Simplify registration extensions
  analyzers/src/SonarAnalyzer.CSharp/Extensions/SonarAnalysisContextExtensions.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/GetHashCodeEqualsOverride.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/GuardConditionOnEqualsOverride.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/StaticFieldWrittenFrom.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/ThisShouldNotBeExposedFromConstructors.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/VariableUnused.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Extensions/SonarAnalysisContextExtensions.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/VariableUnused.cs
Labels: Sprint: Styling

#9047 S2930: Add FP repro for #8336
  analyzers/tests/SonarAnalyzer.Test/TestCases/DisposableNotDisposed.cs
Labels: Sprint: Hardening

#9054 Add ReportIssue overload without Diagnostic
  analyzers/src/SonarAnalyzer.CSharp.Styling/Rules/FileScopeNamespace.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AbstractTypesShouldNotHaveConstructors.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AllBranchesShouldNotHaveSameImplementation.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AlwaysSetDateTimeKind.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AnonymousDelegateEventUnsubscribe.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/ArgumentSpecifiedForCallerInfoParameter.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/ArrayCovariance.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AssertionArgsShouldBePassedInCorrectOrder.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AssertionsShouldBeComplete.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AssignmentInsideSubExpression.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AsyncAwaitIdentifier.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AsyncVoidMethod.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AvoidExcessiveClassCoupling.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AvoidExcessiveInheritance.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AvoidLambdaExpressionInLoopsInBlazor.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/BooleanLiteralUnnecessary.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/BreakOutsideSwitch.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/CallToAsyncMethodShouldNotBeBlocking.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/CallerInformationParametersShouldBeLast.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/CastConcreteTypeToInterface.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/CatchEmpty.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/ClassAndMethodName.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/ClassWithEqualityShouldImplementIEquatable.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/AzureFunctionsCatchExceptions.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/AzureFunctionsReuseClients.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/AzureFunctionsStateless.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/CloudNative/DurableEntityInterfaceRestrictions.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/CollectionPropertiesShouldBeReadOnly.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/CollectionQuerySimplification.cs
  analyzers/src/SonarAnalyzer.Common/AnalysisContext/SonarReportingContextBase.cs
Labels: Sprint: Styling

#9067 Disable RS1036
  .editorconfig
  analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarAnalysisContextTest.Register.cs
  analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarSyntaxNodeReportingContextTest.cs
Labels: Sprint: Styling

#9065 Bump FluentAssertions.Analyzers to 0.31.0
  analyzers/tests/SonarAnalyzer.CSharp.Styling.Test/SonarAnalyzer.CSharp.Styling.Test.csproj
  analyzers/tests/SonarAnalyzer.TestFramework/SonarAnalyzer.TestFramework.csproj
  analyzers/tests/SonarAnalyzer.TestFramework/packages.lock.json
Labels: Sprint: Styling

#9117 Replace XmlSerializer in AnalysisConfigReader
  analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisConfig.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/AnalysisConfigReader.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/ConfigSetting.cs
  analyzers/tests/SonarAnalyzer.Test/Helpers/AnalysisConfigReaderTest.cs
Labels: Sprint: Styling

#9116 Replace XmlSerializer in ProjectConfigReader
  analyzers/src/SonarAnalyzer.Common/Helpers/ProjectConfig.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/ProjectConfigReader.cs
Labels: Sprint: Styling

#9114 Move all ASP.NET rules in a dedicated folder
  analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/RouteTemplateShouldNotStartWithSlash.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/SpecifyRouteAttribute.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/AspNetMvcHelper.cs
  analyzers/src/SonarAnalyzer.Common/Rules/AspNet/BackslashShouldBeAvoidedInAspNetRoutesBase.cs
  analyzers/src/SonarAnalyzer.Common/Rules/AspNet/RouteTemplateShouldNotStartWithSlashBase.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.cs
  analyzers/src/SonarAnalyzer.VisualBasic/Rules/AspNet/RouteTemplateShouldNotStartWithSlash.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/Rules/AspNet/BackslashShouldBeAvoidedInAspNetRoutesTest.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/Rules/AspNet/RouteTemplateShouldNotStartWithSlashTest.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore8AndAbove.CSharp11.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore8AndAbove.vb
  analyzers/tests/SonarAnalyzer.Net8.Test/TestCases/AspNet/RouteTemplateShouldNotStartWithSlash.AspNetCore.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/BackslashShouldBeAvoidedInAspNetRoutesTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/RouteTemplateShouldNotStartWithSlashTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/SpecifyRouteAttributeTest.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNet4x.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNet4x.vb
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore2AndAbove.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore2x.CSharp8.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore2x.vb
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore3AndAbove.CSharp11.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore3AndAbove.vb
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/RouteTemplateShouldNotStartWithSlash.AspNet4x.PartialAutogenerated.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/RouteTemplateShouldNotStartWithSlash.AspNet4x.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/RouteTemplateShouldNotStartWithSlash.AspNet4x.vb
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/RouteTemplateShouldNotStartWithSlash.AspNetCore.PartialAutogenerated.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/RouteTemplateShouldNotStartWithSlash.AspNetCore.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/RouteTemplateShouldNotStartWithSlash.AspNetCore.vb
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/SpecifyRouteAttribute.CSharp12.cs
Labels: Type: Improvement, Sprint: ASP.NET MVC, Sprint: ASP.NET Web API

#9105 New rule S6961 for C#: API Controllers should derive from ControllerBase instead of Controller
  analyzers/rspec/cs/S6961.html
  analyzers/rspec/cs/S6961.json
  analyzers/rspec/cs/Sonar_way_profile.json
  analyzers/src/SonarAnalyzer.CSharp/Rules/AspNet/ApiControllersShouldNotDeriveDirectlyFromController.cs
  analyzers/src/SonarAnalyzer.Common/Helpers/KnownType.cs
  analyzers/tests/SonarAnalyzer.Test/PackagingTests/RuleTypeMappingCS.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/ApiControllersShouldNotDeriveDirectlyFromControllerTest.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/ApiControllersShouldNotDeriveDirectlyFromController.cs
Labels: Sprint: ASP.NET Web API

#9141 Migrate .Net8.Test project to SonarAnalyzer.Test
  analyzers/SonarAnalyzer.sln
  analyzers/tests/SonarAnalyzer.Net8.Test/ReadMe.md
  analyzers/tests/SonarAnalyzer.Net8.Test/Rules/AspNet/BackslashShouldBeAvoidedInAspNetRoutesTest.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/Rules/AspNet/RouteTemplateShouldNotStartWithSlashTest.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/Rules/BypassingAccessibilityTest.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/Rules/MutableFieldsShouldNotBePublicReadonlyTest.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/Rules/MutableFieldsShouldNotBePublicStaticTest.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/Rules/PublicMethodWithMultidimensionalArrayTest.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/Rules/SecurityPInvokeMethodShouldNotBeCalledTest.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/Rules/SelfAssignmentTest.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/Rules/TooManyParametersTest.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/SonarAnalyzer.Net8.Test.csproj
  analyzers/tests/SonarAnalyzer.Net8.Test/TestCases/MutableFieldsShouldNotBePublicReadonly.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/TestCases/MutableFieldsShouldNotBePublicStatic.cs
  analyzers/tests/SonarAnalyzer.Net8.Test/packages.lock.json
  analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/BackslashShouldBeAvoidedInAspNetRoutesTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/AspNet/RouteTemplateShouldNotStartWithSlashTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/BypassingAccessibilityTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/MutableFieldsShouldNotBePublicReadonlyTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/MutableFieldsShouldNotBePublicStaticTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/PublicMethodWithMultidimensionalArrayTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/SecurityPInvokeMethodShouldNotBeCalledTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/SelfAssignmentTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/TooManyParametersTest.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore8AndAbove.CSharp11.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/BackslashShouldBeAvoidedInAspNetRoutes.AspNetCore8AndAbove.vb
  analyzers/tests/SonarAnalyzer.Test/TestCases/AspNet/RouteTemplateShouldNotStartWithSlash.AspNetCore.CSharp12.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/BypassingAccessibility.CSharp12.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/MutableFieldsShouldNotBePublicReadonly.CSharp9.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/MutableFieldsShouldNotBePublicStatic.CSharp9.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/PublicMethodWithMultidimensionalArray.CSharp12.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/SecurityPInvokeMethodShouldNotBeCalled.CSharp12.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/SelfAssignment.CSharp12.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/TooManyParameters_CustomValues.CSharp12.cs
  azure-pipelines.yml
Labels: Sprint: ASP.NET Web API

#9143 Update TestFramework to target net8
  analyzers/tests/SonarAnalyzer.TestFramework.Test/SonarAnalyzer.TestFramework.Test.csproj
  analyzers/tests/SonarAnalyzer.TestFramework.Test/packages.lock.json
  analyzers/tests/SonarAnalyzer.TestFramework/SonarAnalyzer.TestFramework.csproj
  analyzers/tests/SonarAnalyzer.TestFramework/packages.lock.json
  azure-pipelines.yml
Labels: Sprint: ASP.NET Web API

#9197 Delete unused packages.lock.json
  analyzers/tests/SonarAnalyzer.Net8.Test/packages.lock.json
Labels: Sprint: ASP.NET Web API

#9145 Disjoint Sets primitives
  analyzers/src/SonarAnalyzer.Common/Common/DisjointSets.cs
  analyzers/tests/SonarAnalyzer.Test/Common/DisjointSetsTest.cs
Labels: Sprint: ASP.NET Web API
