Repository SonarSource/sonar-dotnet, pull requests merged in 2024-02, with the labels that each got.

#8657 TestFramework: Refactor DiagnosticVerifier.AnalyzerExceptions
  analyzers/tests/SonarAnalyzer.Test/Rules/CheckFileLicenseTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/MethodsShouldNotHaveTooManyLinesTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/SymbolicExecution/SymbolicExecutionRunnerTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
Labels: Sprint: Tests

#8663 TestFramework: Cleanup IssueLocationCollector
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.ExpectedBuildErrors.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.ExpectedIssueLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.FindIssueLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.FindPreciseIssueLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.GetExpectedIssueLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.GetIssueLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.GetPreciseIssueLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/CodeFixVerifier.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/CompilationIssues.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationCollector.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/Verifier.cs
Labels: Sprint: Tests

#8664 TestFramework: Change IssueLocation.IsPrimary to IssueType
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/CompilationIssuesTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.ExpectedBuildErrors.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.ExpectedIssueLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.FindIssueLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.FindPreciseIssueLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.MergeLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationPairTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocation.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationCollector.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationPair.cs
Labels: Sprint: Tests

#8670 TestFramework: Update Verifier syntax docs
  docs/verifier-syntax.md
Labels: Sprint: Tests

#8672 Use C# 12
  analyzers/Analyzers.targets
Labels: Sprint: Tests

#8683 Disable IDE0057
  .editorconfig
Labels: Sprint: Tests

#8688 S2583: Add FP Repro for #8678
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
Labels: Sprint: SE

#8691 S2589: Update reproducer
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
Labels: Sprint: SE

#8673 TestFramework: Refactoring and cleanup
  analyzers/tests/SonarAnalyzer.Test/Rules/DatabasePasswordsShouldBeSecureTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/DisablingRequestValidationTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/DoNotHardcodeCredentialsTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/RequestsWithExcessiveLengthTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/CompilationIssuesTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.MergeLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationPairTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocation.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationCollector.cs
Labels: Sprint: Tests

#8677 TestFramework: Deprecate CompilationErrorBehavior
  analyzers/tests/SonarAnalyzer.Test/AnalysisContext/SonarAnalysisContextBaseTest.ShouldAnalyzeTree.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/DatabasePasswordsShouldBeSecureTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/DisablingRequestValidationTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/DoNotHardcodeCredentialsTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/Hotspots/RequestsWithExcessiveLengthTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/MethodsShouldUseBaseTypesTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/OptionExplicitOnTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/OptionStrictOnTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/TaskConfigureAwaitTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/Verifier.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/VerifierBuilder.cs
Labels: Sprint: Tests

#8694 TestFramework: Bump coverage
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Common/LogTesterTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework/SonarAnalyzer.TestFramework.csproj
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/CompilationIssues.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/SuppressionHandler.cs
Labels: Sprint: Tests

#8699 TestFramework: Refactor LanguageVersion logging
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/CompilationIssuesTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/CompilationIssues.cs
Labels: Sprint: Tests

#8702 SE: Move CollectionConstraint from S4158 to the engine (part 1)
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Binary.Collections.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CollectionTracker.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ObjectCreation.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
Labels: Sprint: SE

#8710 SE: Move CollectionConstraint from S4158 to the engine (part 3)
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Argument.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Binary.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
  analyzers/tests/SonarAnalyzer.Test/TestFramework/SymbolicExecution/ValidatorTestCheck.cs
Labels: Sprint: SE

#8722 TestFramework: Use file scoped namespaces
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Build/ParseOptionsHelperTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Build/SnippetCompilerTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/CodeFixProviderTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierExceptionTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.ExpectedIssueLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.FindIssueLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.FindPreciseIssueLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.MergeLocations.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationCollectorTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/IssueValidation/IssueLocationTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/VerifierBuilderTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/VerifierTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Analyzers/DummyAnalyzer.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Analyzers/DummyCodeFix.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Analyzers/DummyUtilityAnalyzer.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Build/ParseOptionsHelper.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Build/ProjectBuilder.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Build/SnippetCompiler.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Build/SolutionBuilder.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Common/AnalysisScaffolding.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Common/AssertIgnoreScope.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Common/Constants.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Common/CurrentCultureScope.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Common/EnvironmentVariableScope.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Common/FixAllDiagnosticProvider.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Common/LogTester.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Common/Paths.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Common/TestContextHelper.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Common/TestHelper.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Extensions/CompilationExtensions.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Extensions/StringAssertionsExtensions.cs
  analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/AspNetCoreMetadataReference.cs
  analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/CoreMetadataReference.cs
  analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/FrameworkMetadataReference.cs
  analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/MetadataReferenceFacade.cs
  analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/MetadataReferenceFactory.cs
  analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/NuGetMetadataFactory.Package.cs
  analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/NuGetMetadataFactory.cs
  analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/NuGetMetadataReference.cs
  analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/WindowsFormsMetadataReference.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifier.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/IssueLocationCollector.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/Verifier.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/VerifierBuilder.cs
Labels: Sprint: Tests

#8725 TestFramework: Make failed assertions clickable in Rider
  analyzers/tests/SonarAnalyzer.TestFramework.Test/Verification/DiagnosticVerifierExceptionTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/DiagnosticVerifierException.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/IssueValidation/VerificationMessage.cs
Labels: Sprint: Tests

#8732 ITs: Fix imports in IssueParserTests
  analyzers/its/expected/akka.net/S2589-Akka-netstandard2.0.json
  analyzers/its/expected/akka.net/S2589-Akka.Persistence.Sql.Common-netstandard2.0.json
  analyzers/its/expected/akka.net/S4158-Akka.Cluster-netstandard2.0.json
  analyzers/src/ITs.JsonParser/packages.lock.json
  analyzers/tests/ITs.JsonParser.Test/IssueParserTest.cs
  analyzers/tests/ITs.JsonParser.Test/packages.lock.json
Labels: Sprint: Tests

#8742 TestFramework: Fix codesmells
  analyzers/tests/SonarAnalyzer.Test/Rules/ClassAndMethodNameTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/DeadStoresTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/DoNotDecreaseMemberVisibilityTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/EmptyMethodTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/EncryptionAlgorithmsShouldBeSecureTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/InfiniteRecursionTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/InheritedCollidingInterfaceMembersTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/LdapConnectionShouldBeSecureTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/MemberShouldBeStaticTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/MethodOverloadOptionalParameterTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/MethodOverrideAddsParamsTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/MethodOverrideChangedDefaultValueTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/MethodParameterUnusedTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/MethodShouldBeNamedAccordingToSynchronicityTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/ParameterNameMatchesOriginalTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/RedundantArgumentTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/RedundantJumpStatementTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/StaticFieldInitializerOrderTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/StaticFieldWrittenFromInstanceMemberTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/StringOrIntegralTypesForIndexersTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/SymbolicExecution/ConditionEvaluatesToConstantTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/SymbolicExecution/EmptyNullableValueAccessTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/SymbolicExecution/InvalidCastToInterfaceTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/SymbolicExecution/NullPointerDereferenceTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/SymbolicExecution/ObjectsShouldNotBeDisposedMoreThanOnceTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/TrackNotImplementedExceptionTest.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/UnusedPrivateMemberTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Analyzers/DummyAnalyzer.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Analyzers/DummyCodeFix.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Common/FixAllDiagnosticProvider.cs
  analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/MetadataReferenceFacade.cs
  analyzers/tests/SonarAnalyzer.TestFramework/MetadataReferences/NuGetMetadataFactory.Package.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Verification/CodeFixVerifier.cs
Labels: Sprint: Tests

#8741 ITs: Write Sarif in different directory
  analyzers/its/Directory.Build.targets
  analyzers/its/regression-test.ps1
  analyzers/src/ITs.JsonParser/IssueParser.cs
  analyzers/src/ITs.JsonParser/Program.cs
  analyzers/src/ITs.JsonParser/Reports/InputReport.cs
  analyzers/tests/ITs.JsonParser.Test/IssueParserTest.cs
  analyzers/tests/ITs.JsonParser.Test/Sarif.cs
Labels: Sprint: Tests

#8744 ITs: Update minimum dotnet sdk version for .NET 3.1 projects
  analyzers/its/sources/NetCore31/global.json
  analyzers/its/sources/NetCore31WithConfigurableRules/global.json
Labels: Sprint: Tests

#8654 Add IsInLoop property to SymbolicContext
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/LoopDetector.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RoslynSymbolicExecution.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/SymbolicContext.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/LoopDetectorTest.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/SymbolicCheckListTest.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/SymbolicContextTest.cs
  analyzers/tests/SonarAnalyzer.TestFramework/Common/TestHelper.cs
Labels: Sprint: SE

#8751 Update ITs
  analyzers/its/expected/Ember-MM/S2583-generic.EmberCore.XBMC.json
  analyzers/its/expected/Ember-MM/S2589-generic.EmberCore.XBMC.json
  analyzers/its/expected/Ember-MM/generic.EmberCore.XBMC-{6FE33C61-E2C2-4982-9536-63AEF0A98AAA}-S2583.json
  analyzers/its/expected/Ember-MM/generic.EmberCore.XBMC-{6FE33C61-E2C2-4982-9536-63AEF0A98AAA}-S2589.json
  analyzers/its/expected/ManuallyAddedNoncompliantIssues.CS/S2589-IntentionalFindings-netcoreapp2.1.json
Labels: Sprint: SE

#8708 S2583: Add FP Repro for #8707
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
Labels: Sprint: SE

#8733 SE: Move CollectionConstraint from S4158 to the engine (part 6)
  analyzers/its/expected/Net5/S2589-Net5-net5.0.json
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Argument.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ArrayCreation.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CollectionTracker.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.Enumerable.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ObjectCreation.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.vb
Labels: Sprint: SE

#8759 S2589: Add FP Repro for #8570
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
Labels: Sprint: SE

#8760 SE Loops: Addition for same sign operands
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/ArithmeticCalculator.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ArithmeticCalculator.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/CalculationsShouldNotOverflow.vb
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
Labels: Sprint: SE

#8755 Fix S2583/S2589 FP: try-finally in loop
  analyzers/src/SonarAnalyzer.CFG/Extensions/BasicBlockExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/LoopDetector.cs
  analyzers/tests/SonarAnalyzer.Test/Extensions/BasicBlockExtensionsTests.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/LoopDetectorTest.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/ConditionEvaluatesToConstant.cs
Labels: Sprint: SE

#8729 Coding Style update: Do not use `ValueTuples`
  docs/coding-style.md
Labels: Type: Tooling

#8779 Simplify code in `LoopDetector`
  analyzers/src/SonarAnalyzer.CFG/Extensions/BasicBlockExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/LoopDetector.cs
  analyzers/tests/SonarAnalyzer.Test/Extensions/BasicBlockExtensionsTest.cs
Labels: Sprint: SE

#8802 Extract LoggingFrameworkIdentifier
  analyzers/src/SonarAnalyzer.CSharp/Rules/ExceptionsShouldBeLogged.cs
  analyzers/src/SonarAnalyzer.Shared/LoggingFrameworkIdentifier.cs
Labels: Sprint: Logging rules

#8801 Remove 'SonarAnalyzer' prefix from RuleDescriptorGenerator
  analyzers/SonarAnalyzer.sln
  analyzers/src/RuleDescriptorGenerator/Descriptors/Rule.cs
  analyzers/src/RuleDescriptorGenerator/Descriptors/RuleParameter.cs
  analyzers/src/RuleDescriptorGenerator/Program.cs
  analyzers/src/RuleDescriptorGenerator/Properties/AssemblyInfo.cs
  analyzers/src/RuleDescriptorGenerator/RuleDescriptorGenerator.csproj
  analyzers/src/RuleDescriptorGenerator/packages.RuleDescriptorGenerator.config
  analyzers/src/RuleDescriptorGenerator/packages.lock.json
  sonar-csharp-plugin/pom.xml
  sonar-vbnet-plugin/pom.xml
Labels: Type: Tooling

#8803 Rule S6667: Update after peach validation
  analyzers/its/expected/Ember-MM/S6667-Ember.Plugins.json
  analyzers/rspec/cs/S6667.html
  analyzers/rspec/cs/S6667.json
  analyzers/src/SonarAnalyzer.CSharp/Extensions/ArgumentSyntaxExtensions.cs
  analyzers/src/SonarAnalyzer.CSharp/Extensions/InvocationExpressionSyntaxExtensions.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/ExceptionsShouldBeLogged.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/MessageTemplateAnalyzer.cs
  analyzers/src/SonarAnalyzer.Shared/LoggingFrameworkMethods.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/ExceptionsShouldBeLoggedTest.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/ExceptionsShouldBeLogged.cs
Labels: Sprint: Logging rules

#8807 S4790 FN: Add repro
  analyzers/tests/SonarAnalyzer.Test/TestCases/Hotspots/CreatingHashAlgorithms.CSharp11.cs
Labels: Type: False Negative, Area: C#

#8816 Improve S6678: Introduce secondary locations
  analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/UsePascalCaseForNamedPlaceHolders.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/UsePascalCaseForNamedPlaceHoldersTest.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/UsePascalCaseForNamedPlaceHolders.cs
Labels: Sprint: Logging rules

#8815 Template rules update after peach validation
  analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/MessageTemplateAnalyzer.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/NamedPlaceholdersShouldBeUniqueTest.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/NamedPlaceholdersShouldBeUnique.cs
Labels: Sprint: Logging rules

#8820 Template rules update after peach validation part#2
  analyzers/src/SonarAnalyzer.CSharp/Rules/MessageTemplates/MessageTemplateAnalyzer.cs
  analyzers/tests/SonarAnalyzer.Test/Helpers/MessageTemplatesTest.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/NamedPlaceholdersShouldBeUnique.cs
Labels: Sprint: Logging rules

#8806 Promote 7 rules to SonarWay
  analyzers/rspec/cs/S1192.json
  analyzers/rspec/cs/S1244.html
  analyzers/rspec/cs/S127.html
  analyzers/rspec/cs/S1696.html
  analyzers/rspec/cs/S1696.json
  analyzers/rspec/cs/S1994.html
  analyzers/rspec/cs/S2701.html
  analyzers/rspec/cs/S2955.html
  analyzers/rspec/cs/Sonar_way_profile.json
  analyzers/rspec/vbnet/S1192.json
  analyzers/rspec/vbnet/Sonar_way_profile.json
  analyzers/src/SonarAnalyzer.CSharp/sonarpedia.json
  analyzers/src/SonarAnalyzer.VisualBasic/sonarpedia.json
Labels: Sprint: MMF-3645
