Repository SonarSource/sonar-dotnet, pull requests merged in 2024-06, with the labels that each got.

#9424 LVA: Coding style cleanup
  analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/LiveVariableAnalysisBase.cs
  analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
  analyzers/src/SonarAnalyzer.CSharp/LiveVariableAnalysis/SonarCSharpLiveVariableAnalysis.cs
  analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.LocalFunction.cs
  analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.TryCatchFinally.cs
  analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/RoslynLiveVariableAnalysisTest.cs
  analyzers/tests/SonarAnalyzer.Test/LiveVariableAnalysis/SonarLiveVariableAnalysisTest.cs
Labels: Sprint: LVA, Type: Cleanup

#9469 S1854: Add FP repro for #9466, #9467, #9468
  analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs
Labels: Sprint: Hardening

#9474 S1854: Add FP repro for #9471, #9472, #9473
  analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs
Labels: Sprint: Hardening

#9478 S3247 cleanup
  analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
  analyzers/tests/SonarAnalyzer.Test/Rules/CastShouldNotBeDuplicatedTest.cs
Labels: Sprint: Hardening

#9479 Fix S3247 FN: Support structs
  analyzers/its/expected/Nancy/S3247-Nancy-net452.json
  analyzers/its/expected/Nancy/S3247-Nancy-netstandard2.0.json
  analyzers/its/expected/Nancy/S3247-Nancy.ViewEngines.Razor-net452.json
  analyzers/its/expected/akka.net/S3247-Akka-netstandard2.0.json
  analyzers/its/expected/akka.net/S3247-Akka.DistributedData-netstandard2.0.json
  analyzers/its/expected/akka.net/S3247-Akka.Streams-netstandard2.0.json
  analyzers/its/expected/akka.net/S3247-Akka.Tests.Performance-netcoreapp3.1.json
  analyzers/its/expected/akka.net/S3247-Akka.Tests.Shared.Internals-netstandard2.0.json
  analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.CSharp11.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.CSharp12.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.CSharp9.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.cs
Labels: Sprint: Hardening

#9481 Fix S3247 FN: Detect is-as and is-is combinations
  analyzers/its/expected/Nancy/S3247-Nancy-net452.json
  analyzers/its/expected/Nancy/S3247-Nancy-netstandard2.0.json
  analyzers/its/expected/akka.net/S3247-Akka-netstandard2.0.json
  analyzers/its/expected/akka.net/S3247-Akka.Cluster-netstandard2.0.json
  analyzers/its/expected/akka.net/S3247-Akka.Persistence-netstandard2.0.json
  analyzers/its/expected/akka.net/S3247-Akka.Remote-netstandard2.0.json
  analyzers/its/expected/akka.net/S3247-Akka.Streams-netstandard2.0.json
  analyzers/src/SonarAnalyzer.CSharp/Rules/CastShouldNotBeDuplicated.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/CastShouldNotBeDuplicated.cs
Labels: Sprint: Hardening

#9480 LVA: Refactor operation extensions
  analyzers/src/SonarAnalyzer.CFG/Extensions/IOperationExtensions.cs
  analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IOperationExtensions.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/ProgramStateTest.CaptureOperation.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/ProgramStateTest.OperationAndSymbolValue.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Branching.LearnConstraint.cs
Labels: Area: CFG/SE, Sprint: Hardening
