Repository SonarSource/sonar-dotnet, pull requests merged in 2024-07, with the labels that each got.

#9477 Learn NotNull from Invocation separately for operation and symbol
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.ExceptionCandidate.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Loops.cs
Labels: Sprint: Hardening

#9497 SE: Learn from bool collection methods
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IInvocationOperationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.Enumerable.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
Labels: Area: CFG/SE, Sprint: Hardening

#9515 SE: Put InvocationOperation tests for Enumerable methods in their own file
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.Enumerable.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.cs
Labels: Sprint: Hardening, Type: Cleanup

#9513 SE: Add `IInvocationOperationExtensions.GetInstance` tests
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/Extensions/IInvocationOperationExtensions.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/CollectionTracker.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationProcessors/Invocation.Enumerable.cs
  analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/RuleChecks/EmptyCollectionsShouldNotBeEnumeratedBase.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/IInvocationOperationExtensionsTest.cs
  analyzers/tests/SonarAnalyzer.Test/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Invocation.Enumerable.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/SymbolicExecution/Roslyn/EmptyCollectionsShouldNotBeEnumerated.vb
  analyzers/tests/SonarAnalyzer.Test/TestFramework/SymbolicExecution/SETestContext.cs
Labels: Sprint: Hardening, Type: Cleanup

#9535 Detect assignments to FlowCaptureReference operations
  analyzers/its/expected/CSharpLatest/S1854-CSharpLatest-net8.0.json
  analyzers/its/expected/akka.net/S1854-Akka-netstandard2.0.json
  analyzers/src/SonarAnalyzer.CFG/LiveVariableAnalysis/RoslynLiveVariableAnalysis.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/DeadStores.RoslynCfg.cs
  analyzers/src/SonarAnalyzer.CSharp/Rules/DeadStores.cs
  analyzers/tests/SonarAnalyzer.Test/TestCases/DeadStores.RoslynCfg.cs
Labels: Sprint: LVA
